#######################################################
#                                                     #
#                 PACKAGES / SECURITY                 #
#                                                     #
#######################################################

homeassistant:
  customize:
    automation.intruder_alerts:
      icon: mdi:shield-home

#######################################################
#                                                     #
#                     AUTOMATIONS                     #
#                                                     #
#######################################################

automation:
  - alias: Intruder Alerts
    initial_state: on
    trigger:
      - platform: state
        entity_id: binary_sensor.landing_sensor_motion, binary_sensor.kitchen_sensor_motion, binary_sensor.front_door, binary_sensor.back_door
        to: 'on'
      - platform: state
        entity_id: sensor.nest_mode
        to: 'Home'
        from: 'Away'
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: input_select.home_status
          state: 'Away'
        - condition: state
          entity_id: input_select.home_status
          state: 'Holiday'
    action:
      - service: notify.matt
        data_template:
          title: >
            {{ "\uD83D\uDC6E" }} Intruder Alert!
          message: "The {{ trigger.to_state.attributes.friendly_name }} has been triggered."
      - service: script.turn_on
        entity_id: script.request_location_update
      - delay: '00:01:00'
