title: Config
path: config
icon: mdi:settings
background: var(--background-image)
cards:  
  - type: custom:compact-custom-header
    header: true
    menu: false
    notification: false
    voice: false
    options: true
    clock: options
    clock_format: 2
    background_image: true

  - type: vertical-stack
    cards:
    - type: horizontal-stack
      cards:
        - type: custom:button-card
          entity: automation.rain_alert
          name: Rain Watch
          color_type: icon
          icon: attribute
          color: "#0fb9b1"
        - type: custom:button-card
          entity: input_boolean.alarm_clock
          name: Alarm Clock
          color_type: icon
          icon: attribute
          color: "#0fb9b1"
          
    - type: horizontal-stack
      cards:        
        - type: custom:button-card
          entity: input_boolean.guests_staying
          name: Guests Staying
          color_type: icon
          icon: attribute
          color: "#0fb9b1"
        - type: custom:button-card
          entity: input_boolean.entertaining
          name: Keep Lights On
          color_type: icon
          icon: attribute
          color: "#0fb9b1"
    
  - type: entities
    title: Alarm Clock
    show_header_toggle: false
    entities:
      - input_boolean.alarm_clock
      - sensor.alarm_time
      - input_number.alarm_hour
      - input_number.alarm_minutes
  
  - type: vertical-stack
    cards: 
      - type: custom:xiaomi-vacuum-card
        entity: vacuum.xiaomi_vacuum_cleaner
        background: false
        name: Robbie the Rover
        buttons: true
        background: robbie.jpeg
      - type: glance
        columns: 2
        entities:
          - entity: input_boolean.alarm_clock
            tap_action: toggle
          - sensor.alarm_time
          - input_number.alarm_hour
          - input_number.alarm_minutes