title: Config
path: config
icon: mdi:settings
background: var(--background-image)
cards:  
  - type: custom:compact-custom-header
    header: true
    menu: false
    notification: false
    voice: false
    options: true
    clock: options
    clock_format: 2
    background_image: true

  - type: vertical-stack
    cards:
    - type: horizontal-stack
      cards:
        - type: custom:button-card
          entity: automation.rain_alert
          name: Rain Watch
          color_type: icon
          icon: attribute
          color: "#0fb9b1"
        - type: custom:button-card
          entity: input_boolean.alarm_clock
          name: Alarm Clock
          color_type: icon
          icon: attribute
          color: "#0fb9b1"
          
    - type: horizontal-stack
      cards:        
        - type: custom:button-card
          entity: input_boolean.guests_staying
          name: Guests Staying
          color_type: icon
          icon: attribute
          color: "#0fb9b1"
        - type: custom:button-card
          entity: input_boolean.entertaining
          name: Keep Lights On
          color_type: icon
          icon: attribute
          color: "#0fb9b1"
    
  - type: entities
    title: Alarm Clock
    show_header_toggle: false
    entities:
      - input_boolean.alarm_clock
      - sensor.alarm_time
      - input_number.alarm_hour
      - input_number.alarm_minutes

  - type: custom:xiaomi-vacuum-card
    entity: vacuum.xiaomi_vacuum_cleaner
    background: false
    name: Robbie the Rover
    buttons: true
    background: robbie.jpeg
  
########### WIP XIAOMI - RIPPED FROM HASS COMMUNTY https://community.home-assistant.io/t/xiaomi-vacuum-cleaner-card/64456/45


  - type: vertical-stack
    cards:
    - type: picture-elements
      title: Vacuum
      image: '/local/vacuum1.jpg'
      elements:
        - type: icon
          icon: mdi:bell-ring
          tap_action: call-service
          entity: vacuum.xiaomi_vacuum_cleaner
          service: vacuum.locate
          style:
           top: 90%
           left: 80%
           color: '#3090C7'
        - type: icon
          icon: mdi:crosshairs
          tap_action: call-service
          entity: vacuum.xiaomi_vacuum_cleaner
          service: vacuum.clean_spot
          style:
           top: 90%
           left: 65%
           color: '#3090C7'
        - type: icon
          tap_action: call-service
          icon: mdi:home
          entity: vacuum.xiaomi_vacuum_cleaner
          service: vacuum.return_to_base
          style:
           top: 90%
           left: 50%
           color: '#3090C7'
        - type: icon
          icon: mdi:stop
          tap_action: call-service
          entity: vacuum.xiaomi_vacuum_cleaner
          service: vacuum.stop
          style:
           top: 90%
           left: 35%
           color: '#3090C7'
        - type: icon
          icon: mdi:play
          tap_action: call-service
          entity: vacuum.xiaomi_vacuum_cleaner
          service: vacuum.start
          style:
           top: 90%
           left: 20%
           color: '#3090C7'
        - type: state-label
          entity: sensor.vacuum_operation
          style:
           top: 10%
           left: 1%
           color: rgb(255, 255, 255)
           transform: translate(0%,-50%)
           pointer-events: none
           font-family: Trebuchet MS
           font-size: 90%
           font-weight: bold
           border-color: rgb(34, 154, 210)
           background-color: '#3090C7'
           border-radius: 6px
        - type: state-label
          entity: sensor.vacuum_accessories
          style:
           top: 10%
           right: 1%
           color: rgb(255, 255, 255)
           transform: translate(0%,-50%)
           pointer-events: none
           font-family: Trebuchet MS
           font-size: 90%
           font-weight: bold
           border-color: rgb(34, 154, 210)
           background-color: '#3090C7'
           border-radius: 6px
        - type: state-label
          tap_action: more-info
          entity: vacuum.xiaomi_vacuum_cleaner
          style:
           top: 14%
           right: 38%
           color: rgb(255, 255, 255)
           transform: translate(0%,-50%)
           font-family: Trebuchet MS
           font-size: 150%
           font-weight: bold
           border-color: rgb(34, 154, 210)
           border-radius: 6px
           background-color: '#cccccc'
        - type: state-label
          entity: sensor.vacuum_cleanmainbrush
          style:
            top: 35%
            right: 1%
            color: '#ffffff'
            transform: translate(0%,-50%)
            pointer-events: none
            font-family: Trebuchet MS
            font-size: 76%
            font-weight: bold
            border-right-style: solid
            border-color: rgb(34, 154, 210)
        - type: state-label
          entity: sensor.vacuum_cleansidebrush
          style:
            top: 45%
            right: 1%
            color: '#ffffff'
            transform: translate(0%,-50%)
            pointer-events: none
            font-family: Trebuchet MS
            font-size: 76%
            font-weight: bold
            border-right-style: solid
            border-color: rgb(34, 154, 210)
        - type: state-label
          entity: sensor.vacuum_cleanfilter
          style:
            top: 55%
            right: 1%
            color: '#ffffff'
            transform: translate(0%,-50%)
            pointer-events: none
            font-family: Trebuchet MS
            font-size: 76%
            font-weight: bold
            border-right-style: solid
            border-color: rgb(34, 154, 210)
            opacity: 0.8
        - type: state-label
          entity: sensor.vacuum_sensordirtyleft
          style:
            top: 65%
            right: 1%
            color: '#ffffff'
            transform: translate(0%,-50%)
            pointer-events: none
            font-family: Trebuchet MS
            font-size: 76%
            font-weight: bold
            border-right-style: solid
            border-color: rgb(34, 154, 210)
        - type: state-label
          entity: sensor.vacuum_status
          style:
            top: 40%
            left: 1%
            color: '#ffffff'
            transform: translate(0%,-50%)
            pointer-events: none
            font-family: Trebuchet MS
            font-size: 80%
            font-weight: bold
            border-left-style: solid
            border-color: '#3090C7'
        - type: state-label
          entity: sensor.vacuum_battery
          style:
            top: 50%
            left: 1%
            color: '#ffffff'
            transform: translate(0%,-50%)
            pointer-events: none
            font-family: Trebuchet MS
            font-size: 80%
            font-weight: bold
            border-left-style: solid
            border-color: rgb(34, 154, 210)
        - type: state-label
          entity: sensor.vacuum_fan_speed
          style:
            top: 60%
            left: 1%
            color: '#ffffff'
            transform: translate(0%,-50%)
            pointer-events: none
            font-family: Trebuchet MS
            font-size: 80%
            font-weight: bold
            border-left-style: solid
            border-color: rgb(34, 154, 210)
        - type: state-label
          entity: sensor.vacuum_cleaned_area
          prefix: "Area:"
          style:
            top: 79%
            left: 31%
            color: '#84a6ba'
            transform: translate(0%,-50%)
            pointer-events: none
            font-family: Trebuchet MS
            font-size: 80%
            font-weight: bold
        - type: state-label
          entity: sensor.vacuum_cleaning_time
          prefix: "Time:"
          style:
            top: 79%
            left: 51%
            color: '#84a6ba'
            transform: translate(0%,-50%)
            pointer-events: none
            font-family: Trebuchet MS
            font-size: 80%
            font-weight: bold
    - type: entities
      entities:
      - entity: input_select.vacuum_room
    - type: glance
      columns: 2
      entities:
      - entity: input_boolean.disable_dustbin_notification
        name: Disable Notification
      - entity: input_boolean.disable_daily_vacuum
        name: Disable Daily Cleanup