#######################################################
#
#  This installation of Home Assistant uses a package-
#  based configuration format, allowing easy grouping
#  of related components into self-contained files.
#  For more info on packages, see the HA documentation
#
#######################################################

homeassistant:
  name: Home
  temperature_unit: C
  unit_system: metric
  time_zone: !secret timezone
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  whitelist_external_dirs: # Lets us read filesizes
    - /config

  packages: !include_dir_named packages

#######################################################
#                                                     #
#                    CUSTOMISATION                    #
#                                                     #
#######################################################

frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes

lovelace:
  mode: yaml

#######################################################
#                                                     #
#                       ENABLES                       #
#                                                     #
#######################################################

config:

api:

map:

discovery:
  ignore:
    - igd

http:
  base_url: !secret base_url
  ip_ban_enabled: True
  login_attempts_threshold: 15

updater:

history: !include includes/logging.yaml

logbook: !include includes/logging.yaml

recorder:
  purge_interval: 2
  purge_keep_days: 6

logger:
  default: error

mobile_app:
zeroconf:
ssdp:

system_health:
