#######################################################
#
#  This installation of Home Assistant uses a package-   
#  based configuration format, allowing easy grouping
#  of related components into self-contained files.
#  For more info on packages, see the HA documentation
#
#######################################################

homeassistant:
  name: Home
  
  unit_system: metric
  time_zone: !secret timezone
  
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  
  packages: !include_dir_named packages

  #auth_providers:
    #- type: legacy_api_password
    #  api_password: !secret api_password
    #- type: trusted_networks
    #  trusted_networks:
    #  # Allow access to known devices without having to enter a password
    #    - !secret ip_macbook
    #    - !secret ip_matt_phone
    #    - !secret ip_sarah_phone

  
hacs:
  token: !secret github_access_token

script: !include_dir_merge_named includes/scripts