title: Home
resources: !include interface/resources.yaml

## CUSTOM HEADER CONFIG
custom_header: !include interface/custom_header.yaml

# ALLOWS US TO REDUCE REPETITION IN CARDS FOR A MORE DRY CODEBASE
decluttering_templates: !include interface/decluttering_templates.yaml

views:
  - !include interface/view_home.yaml
  - !include interface/view_rooms.yaml
  - !include interface/view_media.yaml
  - !include interface/view_lights.yaml
  - !include interface/view_environment.yaml
  - !include interface/view_security.yaml
  #- !include interface/view_floorplan.yaml
  #- !include interface/view_config.yaml
  - !include interface/view_debug.yaml
