# @link https://github.com/custom-cards/button-card

pretty_device:
  show_icon: true
  show_name: true
  show_last_changed: true
  card_size: 6
  color: rgb(255,255,255)
  tap_action:
    action: more-info
  styles:
    card:
      - height: 60px
      - border: 0px
      - border-radius: 4px
      - font-size: 10px
      #- text-shadow: '1px 1px #0007'
    name:
      - font-weight: bold
      - font-size: 12px
  state:
    - value: "off"
      styles:
        card:
          - background-color: '#b33939'
          - color: white
    - value: "on"
      styles:
        card:
          - background-color: '#218c74'
          - color: white
    - value: "not_home"
      styles:
        card:
          - background-color: '#b33939'
          - color: white
    - value: "home"
      styles:
        card:
          - background-color: '#218c74'
          - color: white

pretty_button:
  color_type: icon
  color: auto-no-temperature
  size: 30%
  aspect_ratio: 2/1
  state:
    - value: 'on'
      styles:
        card:
          - background-color: 'var(--state-icon-active-color)'
          - color: 'var(--sidebar-background-color)'
        icon:
          - color: 'var(--sidebar-background-color)'
        name:
          - color: 'var(--sidebar-background-color)'
