  # Enqueues custom CSS for Google Fonts
  - type: css
    url: 'https://fonts.googleapis.com/css2?family=Barlow:wght@200;400&family=Montserrat:wght@500&display=swap'
  - url: /local/styles.css?v=0.2
    type: css
  # Dependency for many of the custom cards used
  # @link https://github.com/thomasloven/lovelace-card-tools
  - url: /hacsfiles/lovelace-card-tools/card-tools.js
    type: module  # Automatically populate lovelace cards with entities matching certain criteria
  # @link https://github.com/thomasloven/lovelace-auto-entities
  - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
    type: module  # Simple card for Xiaomi (and other) robot vaccums in Home Assistant's Lovelace UI
  # @link https://github.com/benct/lovelace-xiaomi-vacuum-card
  - url: /hacsfiles/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js
    type: module
  # Lovelace Button card for your entities.
  # @link https://github.com/custom-cards/button-card
  - url: /hacsfiles/button-card/button-card.js
    type: module
  # Reuse multiple times the same card configuration with variables to declutter your config.
  # @link https://github.com/custom-cards/decluttering-card
  - url: /hacsfiles/decluttering-card/decluttering-card.js
    type: module
  # A minimalistic yet customizable media player card for Home Assistant Lovelace UI.
  # @link https://github.com/kalkih/mini-media-player
  - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
    type: module
  # A minimalistic and customizable graph card for Home Assistant Lovelace UI.
  # @link https://github.com/kalkih/mini-graph-card
  - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
    type: module
  # Add a slider to rows in lovelace entities cards.
  # @link https://github.com/thomasloven/lovelace-slider-entity-row
  - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
    type: module
  # A card to display upcoming episodes and movies from services like: Plex, Kodi, Radarr, Sonarr, and Trakt.
  # @link https://github.com/custom-cards/upcoming-media-card
  - url: /hacsfiles/upcoming-media-card/upcoming-media-card.js
    type: module
  # Customizable Animated Bar card for Home Assistant Lovelace
  # @link https://github.com/custom-cards/bar-card
  - url: /hacsfiles/bar-card/bar-card.js
    type: module
  # A foldable row for entities card, containing other rows
  # @link https://github.com/thomasloven/lovelace-fold-entity-row
  - url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js
    type: module
  # Vertical Style is a custom Lovelace card for Home Assistant who let you group diferent cards in one card, with diferent style options, like title, card color, to have a border or not.
  # @link https://github.com/matisaul/vertical-style-card
  - url: /local/community/vertical-style-card-master/vertical-style-card.js?v=0.1
    type: module

  # group multiple cards into one card without the borders
  # @link https://github.com/custom-cards/stack-in-card
  - url: /local/community/stack-in-card/stack-in-card.js
    type: module


  # Apply restrictions to Lovelace cards
  # @link https://github.com/iantrich/restriction-card
  - url: /hacsfiles/restriction-card/restriction-card.js
    type: module


  - url: /hacsfiles/lovelace-card-mod/card-mod.js
    type: module

  - url: /hacsfiles/spotify-card/spotify-card.js
    type: module
