#######################################################
#                                                     #
#           PACKAGES / HOLIDAY / MOCKUPANCY           #
#                                                     #
#######################################################

homeassistant:
  customize_glob:
    "*holiday_lights*":
      hidden: true
      icon: mdi:island

#######################################################
#                                                     #
#                     AUTOMATIONS                     #
#                                                     #
#######################################################

# THESE AUTOMATIONS TRIGGER ONLY IF HOME STATUS IS SET TO HOLIDAY

automation:
  - alias: Holiday Lights - AM Workdays
    trigger:
      - platform: time
        at: '06:10:00'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_select.home_status
          state: 'Holiday'
        - condition: state
          entity_id: 'binary_sensor.workday_sensor'
          state: 'on'
    action:
      - service: light.turn_on
        data:
          entity_id: light.master_bedroom
          rgb_color: [172,138,78]
          transition: 10
      - delay: '00:10:00'
      - service: input_select.select_option
        data:
          entity_id: input_select.scene_dining_room
          option: "Dimmed"
      - service: scene.turn_on
        entity_id: scene.hallway_dimmed
      - delay: '01:50:00'
      - service: light.turn_off
        entity_id: group.all_lights

  - alias: Holiday Lights - AM Non Workdays
    trigger:
      - platform: time
        at: '08:15:00'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_select.home_status
          state: 'Holiday'
        - condition: state
          entity_id: 'binary_sensor.workday_sensor'
          state: 'off'
    action:
      - service: light.turn_on
        data:
          entity_id: light.master_bedroom
          rgb_color: [172,138,78]
          transition: 10
      - delay: '00:10:00'
      - service: input_select.select_option
        data:
          entity_id: input_select.scene_dining_room
          option: "Dimmed"
      - service: scene.turn_on
        entity_id: scene.hallway_dimmed
      - delay: '01:15:00'
      - service: light.turn_off
        entity_id: group.all_lights

  - alias: Holiday Lights - PM
    trigger:
      - platform: time
        at: '18:00:00'
    condition:
      - condition: state
        entity_id: input_select.home_status
        state: 'Holiday'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.scene_dining_room
          option: "Neutral"
      - service: scene.turn_on
        entity_id: scene.hallway_dimmed
      - delay: '02:30:00'
      - service: input_select.select_option
        data:
          entity_id: input_select.scene_master_bedroom
          option: "Bedtime"
      - delay: '01:00:00'
      - service: light.turn_off
        entity_id: group.all_lights
