#######################################################
#                                                     #
#                 PACKAGES / DOOR BELL                #
#                                                     #
#######################################################

# @link https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Xiaomi-WXKG01LM

homeassistant:
  customize_glob:
    "*.doorbell*":
      icon: mdi:bell-ring

#######################################################
#                                                     #
#                    INPUT BOOLEAN                    #
#                                                     #
#######################################################

input_boolean:
  doorbell_pressed:
    name: Doorbell Pressed
    initial: off

#######################################################
#                                                     #
#                     AUTOMATIONS                     #
#                                                     #
#######################################################

automation:
  # PLAYS AN MP3 ON SPEAKERS IF DOORBELL HAS NOT BEEN PRESSED WITHIN LAST 3 SECONDS
  # NOTE: THIS IS ASSISTED BY INPUT_BOOLEAN
  - alias: Doorbell
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: doorbell
          event: 1000
    condition:
      - condition: state
        entity_id: input_boolean.doorbell_pressed
        state: 'off'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.doorbell_pressed
      - service: notify.matt_all
        data_template:
          title: >
            {{ "\ud83d\udd14" }} Someone's at the door!
          message: "The doorbell has been pressed."
          data:
            push:
              thread-id: "home-monitoring"
            apns_headers:
              apns-collapse-id: 'doorbell'
      - service: media_player.play_media
        data_template:
          entity_id: media_player.speakers
          media_content_id: https://home.lynwood.club/local/doorbell.mp3
          media_content_type: 'audio/mp3'
  - alias: Doorbell - RESET
    trigger:
      platform: state
      entity_id: input_boolean.doorbell_pressed
      to: 'on'
      for:
        seconds: 3
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.doorbell_pressed
