#######################################################
#                                                     #
#                PACKAGES / FRIDGE DOOR               #
#                                                     #
#######################################################

homeassistant:
  customize_glob:
    "*.fridge_door*":
      icon: mdi:fridge
  customize:
    binary_sensor.fridge_door:
      friendly_name: Fridge Door
    binary_sensor.freezer_door:
      icon: mdi:fridge
      friendly_name: Freezer Door

#######################################################
#                                                     #
#                     AUTOMATIONS                     #
#                                                     #
#######################################################

automation:
  # SENDS A NOTIFICATION IF FRIDGE / FREEZER DOOR OPEN TOO LONG
  - alias: Fridge Door - Notification
    trigger:
      - platform: state
        entity_id: binary_sensor.fridge_door
        to: 'on'
        for:
          minutes: 10
      - platform: state
        entity_id: binary_sensor.fridge_door
        to: 'on'
        for:
          minutes: 15
      - platform: state
        entity_id: binary_sensor.fridge_door
        to: 'on'
        for:
          minutes: 30
      - platform: state
        entity_id: binary_sensor.freezer_door
        to: 'on'
        for:
          minutes: 10
      - platform: state
        entity_id: binary_sensor.freezer_door
        to: 'on'
        for:
          minutes: 15
      - platform: state
        entity_id: binary_sensor.freezer_door
        to: 'on'
        for:
          minutes: 30
    action:
      - service: notify.all_phones
        data_template:
          title: '{{ "\u2603\uFE0F" }} Its cold in here!'
          message: 'The {{ trigger.to_state.attributes.friendly_name }} has been open for {{ trigger.for }} minutes!'
