#######################################################
#                                                     #
#                 PACKAGES / PRESENCE                 #
#                                                     #
#######################################################

homeassistant:
  customize_glob:
    "*ping*":
      hidden: true
      icon: mdi:router-wireless
    "device_tracker.*_watch":
      hidden: true
      icon: mdi:watch-variant
    "automation.home_status_*":
      hidden: true
      icon: mdi:home-account
  customize:
    device_tracker.sarahs_ipad:
      hidden: true
    sensor.who_is_home:
      hidden: true
    script.request_location_update:
      icon: mdi:crosshairs
      friendly_name: Request Device Locations
    group.family:
      icon: mdi:account-group
    group.friends:
      icon: mdi:account-group
    group.occupants:
      icon: mdi:account-group
    group.guests:
      icon: mdi:account-group


#######################################################
#                                                     #
#                   DEVICE TRACKERS                   #
#                                                     #
#######################################################

device_tracker:
  - platform: ping
    interval_seconds: 300
    consider_home: 00:16:00
    hosts:
      sarah_ping: !secret ip_sarah_phone
      matt_ping: !secret ip_matt_phone
      aimee: !secret ip_aimee_phone
      james: !secret ip_james_phone
      katt: !secret ip_katt_phone
      rashida: !secret ip_rashida_phone
      #rob: !secret ip_rob_phone
      sarah_watch: !secret ip_sarah_watch
      matt_watch: !secret ip_matt_watch

#######################################################
#                                                     #
#                       SENSOR                        #
#                                                     #
#######################################################

sensor:
  - platform: template
    sensors:
      who_is_home:
        friendly_name: Who is Home
        value_template: >
          {% if is_state('person.sarah', 'home') and is_state('person.matt', 'home') %}
            Matt and Sarah
          {% elif is_state('person.sarah', 'home') and not is_state('person.matt', 'home') %}
            Sarah
          {% elif is_state('person.matt', 'home') and not is_state('person.sarah', 'home') %}
            Matt
          {% else %}
            No one
          {% endif %}

#######################################################
#                                                     #
#                        GROUP                        #
#                                                     #
#######################################################

group:
  occupants:
    name: Occupants
    entities:
      - person.matt
      - person.sarah
      - group.guests
  family:
    name: Family
    entities:
      - device_tracker.aimee
      - device_tracker.james
  friends:
    name: Friends
    entities:
      - device_tracker.katt
      - device_tracker.rashida
#      - device_tracker.rob
  guests:
    name: Guests
    entities:
      - group.friends
      - group.family

#######################################################
#                                                     #
#                    INPUT SELECT                     #
#                                                     #
#######################################################

input_select:
  home_status:
    name: Home Status
    options:
      - Home
      - Away
      - Holiday
    initial: Home
    icon: mdi:home

#######################################################
#                                                     #
#                    INPUT BOOLEAN                    #
#                                                     #
#######################################################

input_boolean:
  guests_staying:
    name: Guests Staying
    initial: off
    icon: mdi:human-male-female
  entertaining:
    name: Keep Lights On At Bedtime (Entertaining)
    initial: off
    icon: mdi:lightbulb-on-outline

#######################################################
#                                                     #
#                     AUTOMATIONS                     #
#                                                     #
#######################################################

automation:
  # TRIGGER HOME / AWAY MODE
  - alias: Home Status - Change
    hide_entity: true
    trigger:
      - platform: state
        entity_id: group.occupants
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.home_status
          option: >
            {% if is_state('group.occupants', 'home') %}
              Home
            {% else %}
              Away
            {% endif %}

  # We use seperate automations here, so that if home_status is changed manually (eg. by input select), the actions still occur.
  - alias: Home Status - Home Actions
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_select.home_status
        to: 'Home'
    action:
      - service: climate.set_away_mode
        data:
          entity_id: climate.hallway
          away_mode: off

  - alias: 'Home Status - Away Actions'
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_select.home_status
        to: 'Away'
    action:
      - service: script.turn_on
        entity_id: script.turn_off_all_hardware
      - service: climate.set_away_mode
        data:
          entity_id: climate.hallway
          away_mode: on

  # ACTIVATE HOLIDAY MODE
  - alias: Home Status - Holiday Actions
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_select.home_status
        to: 'Away'
        for:
          hours: 24
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.home_status
          option: Holiday

  # SEND NOTIFICATION OF STATUS CHANGE
  - alias: Home Status - Notify
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_select.home_status
    action:
      - service: notify.ios_matt
        data_template:
          title: >
            {% if is_state("input_select.home_status", "Holiday") %} {{ "\uD83C\uDFD6" }} Home set to {{ trigger.to_state.state }} mode
            {% else %} {{ "\uD83C\uDFE1" }} Home set to {{ trigger.to_state.state }} mode
            {% endif %}
          message: >
            {% if is_state("input_select.home_status", "Holiday") %} Enjoy your trip!
            {% else %} Home Assistant status updated
            {% endif %}

  # TRIGGER GUEST MODE IF GUESTS ARE HERE AT 2025
  - alias: Guest Modes - Auto ON
    hide_entity: true
    trigger:
      - platform: time
        at: '20:25'
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: group.family
          state: 'home'
        - condition: state
          entity_id: group.friends
          state: 'home'
    action:
      - service: input_boolean.turn_on
        data_template:
          entity_id: >
            {% if is_state("group.family", "home") %} input_boolean.guests_staying
            {% else %} input_boolean.entertaining
            {% endif %}

#######################################################
#                                                     #
#                       SCRIPTS                       #
#                                                     #
#######################################################

script:
  turn_off_all_hardware:
    sequence:
      - service: light.turn_off
        entity_id: group.all_lights
        data:
          transition: 10
      - service: media_player.media_stop
        entity_id: media_player.speakers
      - service: switch.turn_off
        entity_id: group.all_switches
      - service: media_player.turn_off
        entity_id: media_player.philips_tv
