#######################################################
#                                                     #
#                 PACKAGES / PRESENCE                 #
#                                                     #
#######################################################

homeassistant:
  customize_glob:
    "*ping*":
      hidden: true
      icon: mdi:router-wireless
    "device_tracker.*_watch":
      hidden: true
      icon: mdi:watch-variant
    "automation.home_status_*":
      hidden: true
      icon: mdi:home-account
  customize:
    group.all_devices:
      icon: mdi:devices
    script.request_location_update:
      icon: mdi:crosshairs
      friendly_name: Request Device Locations
    group.family:
      icon: mdi:account-group
    group.friends:
      icon: mdi:account-group
    group.occupants:
      icon: mdi:account-group
    group.guests:
      icon: mdi:account-group
    script.turn_off_all_hardware:
      icon: mdi:power
    automation.guest_modes_auto_on:
      icon: mdi:account-group
    device_tracker.sarah:
      entity_picture: /local/people/sarah-thumb.jpg
    device_tracker.matt:
      entity_picture: /local/people/matt-thumb.jpg
    person.sarah:
      entity_picture: /local/people/sarah-thumb.jpg
    person.matt:
      entity_picture: /local/people/matt-thumb.jpg
    automation.person_greeting:
      icon: mdi:text-to-speech

#######################################################
#                                                     #
#                   DEVICE TRACKERS                   #
#                                                     #
#######################################################

device_tracker:
  - platform: ping
    interval_seconds: 180
    consider_home: 00:13:00
    hosts:
      sarah_ping: !secret ip_sarah_phone
      matt_ping: !secret ip_matt_phone
      sarah_watch: !secret ip_sarah_watch
      matt_watch: !secret ip_matt_watch
  - platform: ping
    interval_seconds: 90
    consider_home: 00:20:00
    hosts:
      aimee: !secret ip_aimee_phone
      james: !secret ip_james_phone
      katt: !secret ip_katt_phone
      rashida: !secret ip_rashida_phone
      #rob: !secret ip_rob_phone
      beez: !secret ip_beez_phone
  - platform: tile
    username: !secret tile_email
    password: !secret tile_password

person:
  - name: Matt
    id: matt
    user_id: c1937753d36940ff9bc20222e7c8ffa3
    device_trackers:
      - device_tracker.matt # HASS App
      - device_tracker.matt_ping # Router Ping
      - device_tracker.matt_watch # Router Ping
      - device_tracker.matts_iphone # iCloud
      - device_tracker.matts_apple_watch # iCloud
  - name: Sarah
    id: sarah
    user_id: 6484a01f3d07451aa10113e684fec320
    device_trackers:
      - device_tracker.sarah # HASS App
      - device_tracker.sarah_ping # Router Ping
      - device_tracker.sarah_watch # Router Ping
      - device_tracker.sarah_kents_iphone # iCloud
      - device_tracker.sarahs_apple_watch # iCloud

#######################################################
#                                                     #
#                       SENSOR                        #
#                                                     #
#######################################################

sensor:
  - platform: template
    sensors:
      matt_friendly_location:
        friendly_name: Matt Friendly Location
        value_template: >
          {% if states.person.matt.state == 'home' %}
          Home
          {% elif states.person.matt.state == 'Matt Work' %}
          Work
          {% else %}
          nr. {{states.sensor.matt_geocoded_location.attributes.Thoroughfare}}
          {% endif %}
      sarah_friendly_location:
        friendly_name: Sarah Friendly Location
        value_template: >
          {% if states.person.sarah.state == 'home' %}
          Home
          {% elif states.person.sarah.state == 'Sarah Work' %}
          Work
          {% else %}
          nr. {{states.sensor.sarah_geocoded_location.attributes.Thoroughfare}}
          {% endif %}

#######################################################
#                                                     #
#                        GROUP                        #
#                                                     #
#######################################################

group:
  occupants:
    name: Occupants
    entities:
      - person.matt
      - person.sarah
      - group.guests
  family:
    name: Family
    entities:
      - device_tracker.aimee
      - device_tracker.james
      - device_tracker.beez
  friends:
    name: Friends
    entities:
      - device_tracker.katt
      - device_tracker.rashida
#      - device_tracker.rob
  guests:
    name: Guests
    entities:
      - group.friends
      - group.family

#######################################################
#                                                     #
#                    INPUT SELECT                     #
#                                                     #
#######################################################

input_select:
  home_status:
    name: Home Status
    options:
      - Home
      - Away
      - Holiday
    initial: Home
    icon: mdi:home-account

#######################################################
#                                                     #
#                    INPUT BOOLEAN                    #
#                                                     #
#######################################################

input_boolean:
  guests_staying:
    name: Guests Staying
    initial: off
    icon: mdi:human-male-female
  entertaining:
    name: Keep Lights On At Bedtime (Entertaining)
    initial: off
    icon: mdi:lightbulb-on-outline

#######################################################
#                                                     #
#                     AUTOMATIONS                     #
#                                                     #
#######################################################

automation:
  # TRIGGER HOME / AWAY MODE
  - alias: Home Status - Change
    trigger:
      - platform: state
        entity_id: group.occupants
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.home_status
          option: >
            {% if is_state('group.occupants', 'home') %}
              Home
            {% else %}
              Away
            {% endif %}

  # We use seperate automations here, so that if home_status is changed manually (eg. by input select), the actions still occur.
  - alias: Home Status - Home Actions
    trigger:
      - platform: state
        entity_id: input_select.home_status
        to: 'Home'
    action:
      - service: climate.set_away_mode
        data:
          entity_id: climate.hallway
          away_mode: off

  - alias: 'Home Status - Away Actions'
    trigger:
      - platform: state
        entity_id: input_select.home_status
        to: 'Away'
    action:
      - service: script.turn_on
        entity_id: script.turn_off_all_hardware
      - service: climate.set_away_mode
        data:
          entity_id: climate.hallway
          away_mode: on

  # ACTIVATE HOLIDAY MODE
  - alias: Home Status - Holiday Actions
    trigger:
      - platform: state
        entity_id: input_select.home_status
        to: 'Away'
        for:
          hours: 24
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.home_status
          option: Holiday

  # SEND NOTIFICATION OF STATUS CHANGE
  - alias: Home Status - Notify
    trigger:
      - platform: state
        entity_id: input_select.home_status
    action:
      - service: notify.mobile_app_matts_phone
        data_template:
          title: >
            {% if is_state("input_select.home_status", "Holiday") %} {{ "\uD83C\uDFD6" }} Home set to {{ trigger.to_state.state }} mode
            {% else %} {{ "\uD83C\uDFE1" }} Home set to {{ trigger.to_state.state }} mode
            {% endif %}
          message: >
            {% if is_state("input_select.home_status", "Holiday") %} Enjoy your trip!
            {% else %} Home Assistant status updated
            {% endif %}
          data:
            push:
              thread-id: "home-monitoring"
            apns_headers:
              apns-collapse-id: 'home-status'


  # TRIGGER GUEST MODE IF GUESTS ARE HERE AT 2100
  - alias: Guest Modes - Auto ON
    trigger:
      - platform: time
        at: '21:00'
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: group.family
          state: 'home'
        - condition: state
          entity_id: group.friends
          state: 'home'
    action:
      - service: input_boolean.turn_on
        data_template:
          entity_id: >
            {% if is_state("group.family", "home") %} input_boolean.guests_staying
            {% else %} input_boolean.entertaining
            {% endif %}
      - service: script.tts_engine
        data_template:
          media_player: media_player.downstairs
          tts_message: >
            {{ [
              "It look's like there's some guests in the house so I'll keep the lights on tonight.",
              "My sensors tell me there are some guests over. I'll keep all the lights on unless told otherwise.",
              "Welcome to my esteemed guests. I'll make sure to keep the lights on for you tonight unless I'm told otherwise."
              ] | random }}


  # SAYS HELLO WHEN SOMEONE ARRIVES HOME
  - alias: Person Greeting
    trigger:
      - platform: state
        entity_id:
          - person.matt
          - person.sarah
        to: 'home'
        for: 00:03:00
    action:
      - service: script.tts_engine
        data_template:
          call_no_greeting: 1
          call_no_signoff: 1
          call_full_moon: 1
          call_empty_robbie: 1
          tts_message: >
            {% set person = trigger.entity_id.split('.')[1]|replace('_', ' ')%}
            {{ [
              "Welcome home " ~ person +". I've missed you.",
              "Welcome back home, " ~ person +". It's great to see you.",
              person + " is now in the house. Welcome back!",
              "Welcome Home " ~ person + ". We have missed you. Or at least the rabbits did.",
              "Welcome home, " ~ person +". Put your feet back and rest!",
              "Knock Knock. Who is There? "   ~ person +" is!",
              "Hey there, " ~ person + ". Welcome Home!",
              person + " - you can not hide from Home Assistant. Welcome home.",
              "Hey "  ~ person +". Your arrival has been recorded by the Smartest house in the neighbourhood.",
              "And the house becomes a home. Welcome back " ~ person,
              person + " is now here.  Hash tag Smart Home.",
              "Pardon the interruption but " ~ person +" is home!",
              "My systems are picking up the presence of additional humans. " ~ person +" has been identified as home.",
              "What is that smell?! It must be " ~ person +" arriving home.",
              "My moments of silence are gone. " ~ person +" is now home.",
              "Welcome home " ~ person +". It's great to feel your presence.",
              "Welcome home " ~ person +". The house is just not the same without you.",
              "Is that " ~ person +" I can hear? Welcome home - it's great to have you back."
              ] | random }}

#######################################################
#                                                     #
#                       SCRIPTS                       #
#                                                     #
#######################################################

script:
  turn_off_all_hardware:
    sequence:
      - service: light.turn_off
        entity_id: group.all_lights
        data:
          transition: 10
      - service: media_player.media_stop
        entity_id: media_player.bedroom, media_player.dining_room, media_player.lounge, media_player.office, media_player.man_cave
      - service: switch.turn_off
        entity_id: group.hardware_switches
      - service: media_player.turn_off
        entity_id: media_player.philips_tv
  request_location_update:
    sequence:
      - service: notify.mobile_app_matts_phone
        data:
          message: "request_location_update"
      - service: notify.mobile_app_sarahs_phone
        data:
          message: "request_location_update"
