include:
  domains:
    #- device_tracker
    #- person
    - automation
    - light
  entities:
    - sensor.sunlight_pct
    - binary_sensor.porch_motion
    - binary_sensor.washing_machine_vibration
    - sensor.washing_machine_vibrations
exclude:
  domains:
    - media_player
    - input_boolean
    - input_select
    - climate
    - switch
#    - sensor

