#######################################################
#                                                     #
#              PACKAGES / MEDIA PLAYERS               #
#                                                     #
#######################################################

homeassistant:
  customize_domain:
    media_player:
      icon: mdi:speaker
  customize_glob:
    "*.plex*":
      icon: mdi:plex
    "automation.automated_music_*":
      icon: mdi:music
  customize:
    media_player.bedroom:
      friendly_name: Bedroom
    media_player.lounge:
      friendly_name: Lounge
    media_player.office:
      friendly_name: Office
    media_player.dining_room:
      friendly_name: Dining Room
    media_player.man_cave:
      friendly_name: Man Cave
    media_player.speakers:
      hidden: true
    media_player.upstairs:
      hidden: true
    media_player.downstairs:
      hidden: true
    media_player.spotify:
      icon: mdi:spotify
    media_player.philips_tv:
      icon: mdi:television
    media_player.playstation_4:
      icon: mdi:playstation


#######################################################
#                                                     #
#                     INTEGRATIONS                    #
#                                                     #
#######################################################

# Google
cast:

media_player:
  - platform: plex
    entity_namespace: 'plex'
  - platform: philips_js
    host: !secret ip_philips_tv
    name: Philips TV
    api_version: 6

spotcast:
  username: !secret spotify_username
  password: !secret spotify_password


#######################################################
#                                                     #
#                     AUTOMATIONS                     #
#                                                     #
#######################################################

automation:
  # PLAYS MUSIC ON DINING ROOM, WHEN THE FIRST PERSON GETS HOME BETWEEN 1500-2030
  - alias: Automated Music - Weekday Evening
    trigger:
      - platform: state
        entity_id: input_select.home_status
        to: "Home"
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.workday_sensor
          state: 'on'
        - condition: time
          after: '15:00:00'
        - condition: time
          before: '20:30:00'
    action:
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.dining_room
          volume_level: 0.3
      - service: media_player.play_media
        entity_id: media_player.dining_room
        data:
          media_content_id: 'http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio1_mf_p'
          media_content_type: 'music'

  # PLAYS MUSIC ON DINING ROOM, WHEN KITCHEN MOTION SENSOR TRIGGER BETWEEN 0800-1030 ON NON WORK DAYS
  - alias: Automated Music - Weekend Morning
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_sensor_motion
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.workday_sensor
          state: 'off'
        - condition: time
          after: '08:00:00'
          before: '10:30:00'
    action:
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.dining_room
          volume_level: 0.2
      - service: spotcast.start
        data_template:
          device_name: 'media_player.dining_room'
          uri: >
            {{ [
            'spotify:user:spotify:playlist:37i9dQZF1DXcxacyAXkQDu',
            'spotify:user:spotify:playlist:37i9dQZF1DX0UrRvztWcAU',
            'spotify:user:motown_records:playlist:5mByrIFuUzwKk8H6XnE5BZ',
            'spotify:user:spotify:playlist:37i9dQZF1DWY4lFlS4Pnso',
            'spotify:user:spotify:playlist:37i9dQZF1DX9u7XXOp0l5L',
            'spotify:user:spotify:playlist:37i9dQZF1DWZdL27osEgj6',
            'spotify:user:spotify:playlist:37i9dQZF1DX2sUQwD7tbmL'
            ] | random }}
        # RANDOM PLAYLISTS IN ORDER:
        # Wake up and smell the coffee, Wake up happy, Motown, Hot Hits UK, Happy Tunes, Weekendhygge, Feel Good Indie Rock
          random_song: true
          shuffle: true
          repeat: true
      # TURNS OFF AUTOMATION - TO PREVENT THE AUTOMATION CONTINUALLY FIRING
      # WAITS FOR 2.5 HOURS AND THEN RE-ENABLES
      - service: automation.turn_off
        entity_id: automation.automated_music_weekend_morning
      - delay: '02:35:00'
      - service: automation.turn_on
        entity_id: automation.automated_music_weekend_morning
