#######################################################
#                                                     #
#           PACKAGES / PLEX RECENTLY ADDED            #
#                                                     #
#######################################################

#######################################################
#                                                     #
#                       SENSORS                       #
#                                                     #
#######################################################

sensor:
  - platform: plex_recently_added
    token: !secret plex_token
    host: localhost
    port: 32400
    max: 6
