#######################################################
#                                                     #
#                 PACKAGES / LIGHTING                 #
#                                                     #
#######################################################

homeassistant:

  customize_domain:
    light:
      icon: mdi:ceiling-light

  customize:

    light.all_hue_lights:
      hidden: true
      homebridge_hidden: true
    light.bedroom_entertainment_area:
      hidden: true
      homebridge_hidden: true
    light.dining_room:
      homebridge_hidden: true
      icon: mdi:silverware-variant
    light.dining_room_lamp:
      icon: mdi:floor-lamp
    light.guest_bedroom:
      homebridge_hidden: true
      icon: mdi:hotel
    light.guest_bedroom_opihr:
      icon: mdi:lamp
    light.guest_bedroom_sovereign:
      icon: mdi:lamp
    light.hallway:
      homebridge_hidden: true
      icon: mdi:stairs
    light.hue_go:
      icon: mdi:circle
    light.kitchen:
      homebridge_hidden: true
      icon: mdi:fridge
    light.landing:
      homebridge_hidden: true
      icon: mdi:stairs
    light.lounge:
      homebridge_hidden: true
      icon: mdi:sofa
    light.lounge_lamp:
      icon: mdi:lamp
    light.master_bedroom:
      homebridge_hidden: true
      icon: mdi:hotel
    light.master_bedroom_lightstrip:
      icon: mdi:led-strip
    light.office:
      homebridge_hidden: true
      icon: mdi:desktop-mac
    light.office_lamp:
      icon: mdi:lamp

    switch.fairy_lights:
      icon: mdi:star-four-points
      friendly_name: Fairy Lights
    switch.festoon_lights:
      icon: mdi:white-balance-incandescent
      friendly_name: Festoon Lights
    switch.star_lamp:
      icon: mdi:lamp
      friendly_name: Star Lamp

#######################################################
#                                                     #
#                     INTEGRATIONS                    #
#                                                     #
#######################################################

hue:
  bridges:
    - host: !secret ip_hue_hub
      allow_unreachable: true
      allow_hue_groups: true

#######################################################
#                                                     #
#                     AUTOMATIONS                     #
#                                                     #
#######################################################

automation:
  # TURN ALL LIGHTS OFF IN THE MORNING, IF IT IS LIGHT ENOUGH
  - alias: Lights OFF Morning
    hide_entity: true
    trigger:
      - platform: time
        at: '10:00:00'
      - platform: time
        at: '11:00:00'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: group.all_lights
          state: 'on'
        - condition: numeric_state
          entity_id: sensor.outside_light_level
          above: 5.0
    action:
      - service: light.turn_off
        entity_id: group.all_lights

  # TURN THE DOWNSTAIRS LIGHTS ON BETWEEN 2100-0500 IF ANYONE ARRIVES HOME, AND THE HOUSE LIGHTS ARE CURRENTLY OFF
  - alias: Lights ON Late Home
    hide_entity: true
    trigger:
      - platform: state
        entity_id: person.matt, person.sarah
        to: 'home'
    condition:
      condition: and
      conditions:
        - condition: time
          after: '21:00:00'
          before: '05:00:00'
        - condition: numeric_state
          entity_id: sensor.outside_light_level
          below: 5.0
        - condition: state
          entity_id: group.all_lights
          state: 'off'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.scene_dining_room
          option: "Dimmed"
      - service: scene.turn_on
        entity_id: scene.hallway_dimmed
      - delay: '00:10:00'
      - service: light.turn_off
        entity_id: group.all_lights

  # STANDARD EVENING LIGHTS
  - alias: Lights ON Early Evening
    hide_entity: true
    trigger:
      - platform: numeric_state
        entity_id: sensor.outside_light_level
        below: 5.0
      - platform: state
        entity_id: input_select.home_status
        to: "Home"
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_select.home_status
          state: "Home"
        - condition: numeric_state
          entity_id: sensor.outside_light_level
          below: 5.0
        - condition: time
          before: '21:00:00'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.scene_dining_room
          option: "Relax"
      - service: scene.turn_on
        entity_id: scene.hallway_dimmed
      - service: input_select.select_option
        data:
          entity_id: input_select.scene_lounge
          option: "Relax"
