#######################################################
#                                                     #
#              PACKAGES / OUTSIDE LIGHTS              #
#                                                     #
#######################################################

homeassistant:
  customize_glob:
    "automation.outside_lights_*":
      hidden: true
      icon: mdi:white-balance-incandescent
    "*porch*":
      icon: mdi:outdoor-lamp
  customize:
    switch.festoon_lights:
      icon: mdi:lightbulb-on-outline
      friendly_name: Festoon Lights

### CHECK THIS ACTUALLY WORKS......
ios:
  push:
    categories:
      - name: Turn Off Outside Lights
        identifier: 'outsidelights'
        actions:
          - identifier: 'DECK_LIGHTS_OFF'
            title: 'Yes'
            activationMode: 'background'
            authenticationRequired: false
          - identifier: 'DECK_LIGHTS_ON'
            title: 'No'
            activationMode: 'background'
            authenticationRequired: false

#######################################################
#                                                     #
#                     AUTOMATIONS                     #
#                                                     #
#######################################################

automation:

  # TURNS OUTSIDE LIGHTS ON, IF LOW LIGHT OUTSIDE AND BACK DOOR OPENED
  - alias: Outside Lights - Turn ON
    trigger:
      - platform: state
        entity_id: binary_sensor.back_door
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: time
          after: '17:00:00'
        - condition: sun
          after: sunset
          after_offset: "-00:45:00"
    action:
      - service: switch.turn_on
        entity_id: switch.festoon_lights

  # IF OUTSIDE LIGHTS HAVE BEEN ON FOR 30, 120 MINS, SEND AN ACTIONABLE NOTIFICATION TO TURN OFF
  - alias: Outside Lights - Turn OFF Actionable
    trigger:
      - platform: state
        entity_id: binary_sensor.back_door
        to: 'off'
        for:
          minutes: 30
      - platform: state
        entity_id: binary_sensor.back_door
        to: 'off'
        for:
          minutes: 120
    condition:
      - condition: state
        entity_id: switch.festoon_lights
        state: 'on'
    action:
      - service: notify.all_phones
        data_template:
          title: >
            {{ "\uD83D\uDCA1" }} Turn off outside lights?
          message: "The back door has been closed for {{ trigger.for }}. Would you like me to turn off the outside lights?"
          data:
            push:
              category: "outsidelights"

  # RESULT OF ACTIONABLE NOTIFICATION
  - alias: Outside Lights - Turn OFF YES
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: DECK_LIGHTS_OFF
    action:
      - service: switch.turn_off
        entity_id: switch.festoon_lights
      - service: notify.ios_matt
        data:
          title: 'WORKED'
          message: 'YES'
