#######################################################
#                                                     #
#             PACKAGES / LIGHTING / SCENES            #
#                                                     #
#######################################################

homeassistant:
  customize_glob:
    "input_select.scene_*":
      icon: mdi:brightness-6
    "scene.*_dimmed":
      icon: mdi:brightness-2
    "scene.*_relax":
      icon: mdi:brightness-3
    "scene.*_bedtime":
      icon: mdi:brightness-3
    "scene.*_bright":
      icon: mdi:brightness-5
    "scene.*_energise":
      icon: mdi:brightness-7
    "scene.*_warm":
      icon: mdi:brightness-6
    "scene.*_entertaining":
      icon: mdi:brightness-6
    "automation.*scene*":
      icon: mdi:brightness-6
  customize:
    scene.master_bedroom_wake_up:
      icon: mdi:brightness-3
    scene.lounge_movie_up:
      icon: mdi:brightness-7
    scene.lounge_movie:
      icon: mdi:brightness-2

#######################################################
#                                                     #
#                    INPUT SELECT                     #
#                                                     #
#######################################################

input_select:
  scene_master_bedroom:
    name: Scene
    options:
      - Energise
      - Bright
      - Bedtime
      - Dimmed
      - Relax
      - "-"
    initial: "-"
  scene_man_cave:
    name: Scene
    options:
      - Energise
      - Bright
      - Bedtime
      - Dimmed
      - Relax
      - "-"
    initial: "-"
  scene_dining_room:
    name: Scene
    options:
      - Energise
      - Bright
      - Dimmed
      - Relax
      - Warm
      - Entertaining
      - "-"
    initial: "-"
  scene_lounge:
    name: Scene
    options:
      - Energise
      - Bright
      - Dimmed
      - Relax
      - Warm
      - Movie
      - "-"
    initial: "-"
  scene_office:
    name: Scene
    options:
      - Energise
      - Bright
      - Dimmed
      - Relax
      - "-"
    initial: "-"
  scene_kitchen:
    name: Scene
    options:
      - Energise
      - Bright
      - Dimmed
      - Relax
      - "-"
    initial: "-"

#######################################################
#                                                     #
#                        SCENE                        #
#                                                     #
#######################################################

scene:

  - name: Hallway Dimmed
    entities:
      light.hallway:
        state: on
        transition: 5
        brightness: 5

  - name: Porch Dimmed
    entities:
      light.porch:
        state: on
        transition: 5
        brightness: 5

  - name: Porch Bright
    entities:
      light.porch:
        state: on
        transition: 5
        brightness: 90


  - name: Master Bedroom Energise
    entities:
      light.master_bedroom:
        !include ../../includes/hue-scenes/energise.yaml
  - name: Master Bedroom Bright
    entities:
      light.master_bedroom:
        !include ../../includes/hue-scenes/bright.yaml
  - name: Master Bedroom Bedtime
    entities:
      light.master_bedroom_colour:
        state: on
        brightness: 125
        transition: 5
        rgb_color: [255,44,57]
      light.master_bedroom_lightstrip:
        state: on
        brightness: 57
        transition: 5
        rgb_color: [215,80,255]
  - name: Master Bedroom Dimmed
    entities:
      light.master_bedroom:
        state: on
        brightness: 77
        transition: 5
        rgb_color: [255,207,120]
  - name: Master Bedroom Relax
    entities:
      light.master_bedroom:
        !include ../../includes/hue-scenes/relax.yaml

  - name: Man Cave Energise
    entities:
      light.man_cave_all:
        !include ../../includes/hue-scenes/energise.yaml
  - name: Man Cave Bright
    entities:
      light.man_cave_all:
        !include ../../includes/hue-scenes/bright.yaml
  - name: Man Cave Bedtime
    entities:
      light.man_cave_colour:
        state: on
        brightness: 36
        transition: 5
        rgb_color: [255,163,74]
      light.man_cave_opihr:
        state: on
        brightness: 61
        transition: 5
        rgb_color: [114,148,255]
      light.man_cave_sovereign:
        state: on
        brightness: 70
        transition: 5
        rgb_color: [255,56,119]
      light.matt_desk:
        state: off
  - name: Man Cave Dimmed
    entities:
      light.man_cave_all:
        !include ../../includes/hue-scenes/dimmed.yaml
  - name: Man Cave Relax
    entities:
      light.man_cave_all:
        !include ../../includes/hue-scenes/relax.yaml

  - name: Dining Room Energise
    entities:
      light.dining_room:
        !include ../../includes/hue-scenes/energise.yaml
  - name: Dining Room Bright
    entities:
      light.dining_room:
        !include ../../includes/hue-scenes/bright.yaml
  - name: Dining Room Dimmed
    entities:
      light.dining_room:
        !include ../../includes/hue-scenes/dimmed.yaml
  - name: Dining Room Relax
    entities:
      light.dining_room:
        !include ../../includes/hue-scenes/relax.yaml
  - name: Dining Room Warm
    entities:
      light.dining_room_colour:
        state: on
        transition: 5
        brightness: 174
        color_temp: 448
      light.dining_room_lamp:
        state: off
  - name: Dining Room Entertaining
    entities:
      light.dining_room_colour:
        state: on
        transition: 5
        brightness: 75
        rgb_color: [255,119,75]
      light.dining_room_lamp:
        state: on
        transition: 5
        brightness: 222
        rgb_color: [255,42,201]

  - name: Office Energise
    entities:
      light.office:
        !include ../../includes/hue-scenes/energise.yaml
  - name: Office Bright
    entities:
      light.office:
        !include ../../includes/hue-scenes/bright.yaml
  - name: Office Dimmed
    entities:
      light.office:
        !include ../../includes/hue-scenes/dimmed.yaml
  - name: Office Relax
    entities:
      light.office:
        !include ../../includes/hue-scenes/relax.yaml

  - name: Kitchen Energise
    entities:
      light.kitchen:
        !include ../../includes/hue-scenes/energise.yaml
  - name: Kitchen Bright
    entities:
      light.kitchen:
        !include ../../includes/hue-scenes/bright.yaml
  - name: Kitchen Dimmed
    entities:
      light.kitchen:
        !include ../../includes/hue-scenes/dimmed.yaml
  - name: Kitchen Relax
    entities:
      light.kitchen:
        !include ../../includes/hue-scenes/relax.yaml

  - name: Lounge Energise
    entities:
      light.lounge:
        !include ../../includes/hue-scenes/energise.yaml
  - name: Lounge Bright
    entities:
      light.lounge:
        !include ../../includes/hue-scenes/bright.yaml
  - name: Lounge Dimmed
    entities:
      light.lounge:
        !include ../../includes/hue-scenes/dimmed.yaml
  - name: Lounge Relax
    entities:
      light.lounge:
        !include ../../includes/hue-scenes/relax.yaml
  - name: Lounge Warm
    entities:
      light.lounge_colour:
        state: on
        transition: 5
        brightness: 257
        rgb_color: [255,163,74]
      light.lounge_lamp:
        state: on
        transition: 5
        brightness: 75
        rgb_color: [255,119,75]
      light.hue_go:
        state: off
  - name: Lounge Movie
    entities:
      light.lounge_colour:
        state: on
        transition: 2
        brightness: 40
        rgb_color: [158,14,108]
      light.lounge_lamp:
        state: off
        transition: 2
      light.hue_go:
        state: off
  - name: Lounge Movie Up
    entities:
      light.lounge_colour:
        state: on
        transition: 2
        brightness: 175
        rgb_color: [255,163,74]
      light.lounge_lamp:
        state: on
        transition: 2
        brightness: 40
        rgb_color: [255,119,75]
      light.hue_go:
        state: on
        transition: 2
        brightness: 20
        rgb_color: [255,119,75]

#######################################################
#                                                     #
#                     AUTOMATIONS                     #
#                                                     #
#######################################################

automation:
  - alias: Scene SELECT
    trigger:
      - platform: state
        entity_id: input_select.scene_master_bedroom, input_select.scene_man_cave, input_select.scene_lounge, input_select.scene_dining_room, input_select.scene_office
    condition:
      - condition: template
        value_template: >
          {{ not is_state('{{ trigger.entity_id }}', '-') }}
    action:
      - service: scene.turn_on
        data_template:
          entity_id: "scene.{{ trigger.entity_id|replace('input_select.scene_', '') }}_{{ trigger.to_state.state }}"

  - alias: Scene RESET
    trigger:
      - platform: state
        entity_id: light.master_bedroom, light.man_cave, light.lounge, light.dining_room, light.office
        to: 'off'
    action:
      - service: input_select.select_option
        data_template:
          entity_id: "input_select.scene_{{ trigger.entity_id|replace('light.', '') }}"
          option: "-"
