title: Environment
path: environment
icon: mdi:thermometer-lines
visible:
  - user: c1937753d36940ff9bc20222e7c8ffa3

cards:

  - type: vertical-stack
    cards:
    - type: custom:decluttering-card
      template: pretty_graph
      variables:
        - entity: sensor.hallway_thermostat_temperature
        - name: Hallway Temperature
        - color: '#b33939'
    - type: custom:decluttering-card
      template: pretty_graph
      variables:
        - entity: sensor.sunlight_pct
        - name: Sunlight Percent
        - color: '#cd6133'
    - type: custom:decluttering-card
      template: pretty_graph
      variables:
        - entity: sensor.hallway_thermostat_humidity
        - name: Hallway Humidity
        - color: '#34ace0'
    - type: custom:button-card
      template: pretty_button
      entity: automation.rain_alerts
      name: Rain Alerts

  - type: vertical-stack
    cards:
    - type: custom:decluttering-card
      template: pretty_graph
      variables:
        - entity: sensor.kitchen_sensor_temperature
        - name: Kitchen Temperature
        - color: '#b33939'
    - type: custom:decluttering-card
      template: pretty_graph
      variables:
        - entity: sensor.kitchen_sensor_light_level
        - name: Kitchen Lux
        - color: '#cd6133'
    - type: custom:decluttering-card
      template: pretty_graph
      variables:
        - entity: sensor.chance_of_rain
        - name: Chance of Rain
        - color: '#34ace0'

  - type: vertical-stack
    cards:
    - type: custom:decluttering-card
      template: pretty_graph
      variables:
        - entity: sensor.landing_sensor_temperature
        - name: Landing Temperature
        - color: '#b33939'
    - type: custom:decluttering-card
      template: pretty_graph
      variables:
        - entity: sensor.landing_sensor_light_level
        - name: Landing Lux
        - color: '#cd6133'
    - type: custom:decluttering-card
      template: pretty_graph
      variables:
        - entity: sensor.darksky_temperature
        - name: Outside Temperature
        - color: '#34ace0'


