title: Security
path: security
icon: mdi:shield-home
background: var(--background-image)

cards:
  - type: vertical-stack
    cards:
    - type: entities
      title: Home Status
      show_header_toggle: false
      entities:
        - input_select.home_status

    - type: custom:decluttering-card
      template: pretty_button
      variables:
        - entity: automation.intruder_alerts
        - name: Intruder Alerts
        - lock: true

  - type: vertical-stack
    cards:
    - type: entities
      title: Sensors
      show_header_toggle: false
      entities:
        - binary_sensor.kitchen_sensor_motion
        - binary_sensor.landing_sensor_motion
        - binary_sensor.back_door_sensor
        - binary_sensor.front_door_sensor
        - binary_sensor.fridge_door_sensor
        - binary_sensor.freezer_door_sensor
