title: Environment
path: environment
icon: mdi:thermometer-lines

cards:

  - type: vertical-stack
    cards:
    - type: custom:decluttering-card
      template: pretty_graph
      variables:
        - entity: sensor.hallway_thermostat_temperature
        - name: Hallway Temperature
        - color: 'var(--ui-red)'
    - type: custom:decluttering-card
      template: pretty_graph
      variables:
        - entity: sensor.outside_light_level
        - name: Outside Light Level
        - color: 'var(--ui-orange)'
    - type: custom:decluttering-card
      template: pretty_graph
      variables:
        - entity: sensor.hallway_thermostat_humidity
        - name: Hallway Humidity
        - color: 'var(--ui-accent-2)'
    - type: custom:button-card
      template: pretty_button
      entity: automation.rain_alerts
      name: Rain Alerts

  - type: vertical-stack
    cards:
    - type: custom:decluttering-card
      template: pretty_graph
      variables:
        - entity: sensor.kitchen_sensor_temperature
        - name: Kitchen Temperature
        - color: 'var(--ui-red)'
    - type: custom:decluttering-card
      template: pretty_graph
      variables:
        - entity: sensor.kitchen_sensor_light_level
        - name: Kitchen Lux
        - color: 'var(--ui-orange)'
    - type: custom:decluttering-card
      template: pretty_graph
      variables:
        - entity: sensor.chance_of_rain
        - name: Chance of Rain
        - color: 'var(--ui-accent-2)'

  - type: vertical-stack
    cards:
    - type: custom:decluttering-card
      template: pretty_graph
      variables:
        - entity: sensor.landing_sensor_temperature
        - name: Landing Temperature
        - color: 'var(--ui-red)'
    - type: custom:decluttering-card
      template: pretty_graph
      variables:
        - entity: sensor.landing_sensor_light_level
        - name: Landing Lux
        - color: 'var(--ui-orange)'
    - type: custom:decluttering-card
      template: pretty_graph
      variables:
        - entity: sensor.darksky_temperature
        - name: Outside Temperature
        - color: 'var(--ui-accent-2)'


