title: Security
path: security
icon: mdi:shield-home

cards:
  - type: vertical-stack
    cards:
    - type: entities
      title: Home Status
      show_header_toggle: false
      entities:
        - input_select.home_status

    - type: custom:button-card
      template: pretty_button
      entity: automation.intruder_alerts
      lock:
        enabled: true
        duration: 5

  - type: vertical-stack
    cards:
    - type: entities
      title: Sensors
      show_header_toggle: false
      entities:
        - binary_sensor.kitchen_sensor_motion
        - binary_sensor.landing_sensor_motion
        - binary_sensor.washing_machine_vibration
        - binary_sensor.porch_motion
        - binary_sensor.back_door
        - binary_sensor.front_door
        - binary_sensor.fridge_door
        - binary_sensor.freezer_door
