automation:
  - alias: Friends Entrance Music
    trigger:
      - platform: state
        entity_id: device_tracker.katts_phone, device_tracker.rob, device_tracker.aimee, device_tracker.lucy
        to: 'home'
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: input_select.bedtime_trigger
        state: 'Off'
      - condition: time
        after: '09:00:00'
        before: '22:00:00'
    action:
      - service: script.tts_engine
        data_template:
          media_player: media_player.speakergroup_downstairs
          call_no_greeting: 1
          call_no_signoff: 1
          tts_message: >
            {% set trigger_name = trigger.to_state.attributes.friendly_name %}
            {{ [
            "Hello, " ~ trigger_name +". Let's rock.",
            "Hello, " ~ trigger_name +". I've missed you.",
            "Hello, " ~ trigger_name +". How have you been?",
            "Boy am I glad to see you, " ~ trigger_name +".",
            "Hello, " ~ trigger_name +".",
            "Howdy, " ~ trigger_name +".",
            "I think I hear " ~ trigger_name +". Hello!",
            "What's up, " ~ trigger_name +".",
            "Hey, " ~ trigger_name +". It's great to feel your presence."
            ] | random }}
      # Delay allows TTS to put together the notification otherwise the wait template would activate immediately
      - delay: '00:00:05'
      - wait_template: "{{ is_state('media_player.speakergroup_downstairs', 'idle') or is_state('media_player.speakergroup_downstairs', 'off') }}"
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.speaker_dining_room
          volume_level: >
            {% if now().strftime('%H')|int < 10 and now().strftime('%H')|int > 6 %}
              0.15
            {% elif now().strftime('%H')|int > 10 and now().strftime('%H')|int < 20 %}
              0.35
            {% else %}
              0.2
            {% endif %}
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.speaker_lounge
          volume_level: >
            {% if now().strftime('%H')|int < 10 and now().strftime('%H')|int > 6 %}
              0.15
            {% elif now().strftime('%H')|int > 10 and now().strftime('%H')|int < 20 %}
              0.35
            {% else %}
              0.2
            {% endif %}
      - service: spotcast.start
        data_template:
          device_name: 'Downstairs'
          uri: >
            {% if ( trigger.to_state.attributes.friendly_name ) == "Katt" %}
              spotify:track:60AtF9l5YTgVPgJFzA7AGo
            {% elif ( trigger.to_state.attributes.friendly_name ) == "Rob" %}
              spotify:track:6nVijDYMA3KaBGdWabaLvm
            {% elif ( trigger.to_state.attributes.friendly_name ) == "Lucy" %}
              spotify:track:5EbX5xL3O2xT8FxCpYzgUO
            {% else %}
              spotify:track:0COqiPhxzoWICwFCS4eZcp
            {% endif %}
