#######################################################
#                                                     #
#                 PACKAGES / BEDTIME                  #
#                                                     #
#######################################################

homeassistant:
  customize_glob:
    "*bedtime*":
      icon: mdi:hotel
  customize:
    script.turn_off_bedtime:
      icon: mdi:power

#######################################################
#                                                     #
#                    INPUT SELECT                     #
#                                                     #
#######################################################

input_select:
  bedtime_trigger:
    name: Bedtime Trigger
    options:
      - "Off"
      - Lights On
      - Asleep
    initial: "Off"

#######################################################
#                                                     #
#                     AUTOMATIONS                     #
#                                                     #
#######################################################

automation:
  # TURN ON BEDROOM LIGHTS WHEN LANDING MOTION SENSOR TRIPPED BETWEEN 20:30 and 04:00
  - alias: Bedtime Lights ON
    hide_entity: true
    trigger:
      - platform: state
        entity_id: binary_sensor.landing_sensor_motion
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_select.bedtime_trigger
          state: 'Off'
        - condition: time
          after: '20:30:00'
          before: '04:00:00'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.bedtime_trigger
          option: "Lights On"
      - service: input_select.select_option
        data:
          entity_id: input_select.scene_master_bedroom
          option: "Bedtime"
      - service_template: >
          {% if is_state('input_boolean.guests_staying', 'on') %}
            input_select.select_option
            data:
              entity_id: input_select.scene_guest_bedroom
              option: "Bedtime"
          {% endif %}

  # STANDARD SHUT DOWN IF NO GUESTS STAYING, AND IF NO ONE IS LEFT DOWNSTAIRS
  - alias: Bedtime - SHUTDOWN Standard
    hide_entity: true
    trigger:
      - platform: state
        entity_id: light.master_bedroom
        to: 'off'
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: input_select.bedtime_trigger
        state: Lights On
      - condition: state
        entity_id: input_boolean.entertaining
        state: 'off'
      - condition: or
        conditions:
        - condition: state
          entity_id: input_boolean.guests_staying
          state: 'off'
        - condition: and
          conditions:
          - condition: state
            entity_id: input_boolean.guests_staying
            state: 'on'
          - condition: state
            entity_id: light.guest_bedroom
            state: 'off'
    action:
      - service: script.turn_on
        entity_id: script.turn_off_bedtime
      - service: script.turn_on
        entity_id: script.bedtime_message

  # IF GUESTS ARE STAYING AND THEIR BEDROOM LIGHT IS THE LAST TO TURN OFF, TURN OFF ALL DEVICES THEREAFTER
  - alias: Bedtime - SHUTDOWN Guests
    hide_entity: true
    trigger:
      - platform: state
        entity_id: light.guest_bedroom
        to: 'off'
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: input_select.bedtime_trigger
        state: Lights On
      - condition: and
        conditions:
        - condition: state
          entity_id: input_boolean.guests_staying
          state: 'on'
        - condition: state
          entity_id: light.master_bedroom
          state: 'off'
    action:
      - service: script.turn_on
        entity_id: script.turn_off_bedtime

  # IF SOMEONE IS STILL DOWNSTAIRS AT NIGHT, WAIT FOR THEM TO TURN OFF ALL LIGHTS BEFORE SHUTTING DOWN OTHER DEVICES
  - alias: Bedtime - SHUTDOWN Entertaining
    hide_entity: true
    trigger:
      - platform: state
        entity_id: group.all_lights
        to: 'off'
    condition:
      - condition: state
        entity_id: input_boolean.entertaining
        state: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.entertaining
      - service: script.turn_on
        entity_id: script.turn_off_bedtime

  # Bedtime trigger reset at 04:01 as 04:00 is the latest it can be set. If this is unset after we wake up, we will get false flags if the bedroom light is turned off
  - alias: Bedtime - Trigger RESET
    hide_entity: true
    trigger:
      - platform: time
        at: '04:01:00'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.bedtime_trigger
          option: "Off"

#######################################################
#                                                     #
#                       SCRIPTS                       #
#                                                     #
#######################################################

script:
  bedtime_message:
    sequence:
      - wait_template: "{{ is_state('media_player.bedroom', 'idle') or is_state('media_player.bedroom', 'off') }}"
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.bedroom
          volume_level: 0.5
      - service: tts.google_translate_say
        entity_id: media_player.bedroom
        data_template:
          message: >
            Good night {{ states.sensor.who_is_home.state }}.
            {% if is_state('input_boolean.alarm_clock', 'on') %}
            Your alarm is set for {{ states.sensor.alarm_time.state }}AM.
            {% endif %}
            Tomorrow the weather will be {{ states.sensor.darksky_summary_1d.state }} with highs of {{ states. sensor.darksky_daytime_high_temperature_1d.state }} degrees celcius.
            {{ [
            "Sweet dreams!",
            "Sleep tight!",
            "Sleep well!",
            "Rest your weary head!",
            "Good night",
            "Night night",
            "Until tomorrow..good night.",
            "Seeya!",
            "Have a great sleep",
            "Dream of powderdust and unicorns and glitter and pink and sparkles.",
            "Powering down...",
            "Rest up",
            "Please don't snore tonight.",
            "Good night, sleep tight, hope the bedbugs don't bite",
            "Sweet dreams are made of this",
            "Dream a little dream of me"
            ] | random }}
      - wait_template: "{{ is_state('media_player.bedroom', 'idle') }}"
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.bedroom
          volume_level: 0.2
  turn_off_bedtime:
    sequence:
      - service: light.turn_off
        entity_id: group.all_lights
        data:
          transition: 5
      - service: input_select.select_option
        data:
          entity_id: input_select.bedtime_trigger
          option: Asleep
      - service: automation.turn_off
        entity_id: automation.rain_alert
      - service: media_player.media_stop
        entity_id: media_player.speakers
      - service: switch.turn_off
        entity_id: switch.fairy_lights, switch.star_lamp, switch.festoon_lights
      - service: media_player.turn_off
        entity_id: media_player.philips_tv
