#######################################################
#                                                     #
#                PACKAGES / ENVIRONMENT               #
#                                                     #
#######################################################

homeassistant:
  customize:
    climate.hallway:
      friendly_name: Thermostat
      entity_picture: /local/nest.png
    sensor.hallway_thermostat_humidity:
      friendly_name: Humidity
      icon: mdi:water
    sensor.hallway_thermostat_temperature:
      friendly_name: Hallway Temperature
    sensor.hallway_thermostat_operation_mode:
      icon: mdi:settings-box
    binary_sensor.is_workday_tomorrow:
      hidden: true
    binary_sensor.workday_sensor:
      hidden: true

    sensor.average_home_temperature:
      icon: mdi:thermometer
    sensor.time_of_day:
      icon: mdi:calendar-clock

  customize_glob:
    "binary_sensor.*workday*":
      icon: mdi:calendar-outline

#######################################################
#                                                     #
#                     INTEGRATIONS                    #
#                                                     #
#######################################################

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

#######################################################
#                                                     #
#                       ENABLES                       #
#                                                     #
#######################################################

sun:

zone:
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    elevation: !secret home_elevation
    radius: 150
    icon: mdi:home
  - name: Matt Work
    friendly_name: Work
    latitude: !secret work_latitude
    longitude: !secret work_longitude
    radius: 150
    icon: mdi:worker
  - name: Sarah Work
    friendly_name: Work
    latitude: !secret work_sarah_latitude
    longitude: !secret work_sarah_longitude
    radius: 150
    icon: mdi:worker

#######################################################
#                                                     #
#                    BINARY SENSOR                    #
#                                                     #
#######################################################

binary_sensor:
  - platform: workday
    country: UK
  - platform: workday
    name: Is Workday Tomorrow
    country: UK
    days_offset: 1

#######################################################
#                                                     #
#                       SENSOR                        #
#                                                     #
#######################################################

sensor:
  # CURRENT TIME
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
  # AVERAGE HOME TEMP
  - platform: min_max
    name: Average Home Temperature
    type: mean
    entity_ids:
      - sensor.hallway_thermostat_temperature
      - sensor.kitchen_temperature
      - sensor.landing_temperature
  # SO THAT SARAH CAN HOWL AT THE MOON
  - platform: moon