########################################
#                                      #
# This file defines what is logged in  #
# Home Assistant's History and Logbook #
#                                      #
########################################

include:
  domains:
    - climate
    - device_tracker
  entities:
    - group.occupants
    - binary_sensor.matt_bayesian
    - binary_sensor.sarah_bayesian
    - input_select.home_status
    - input_select.bedtime_trigger
    - sensor.average_home_temperature
    - sensor.chance_of_rain
    - sensor.darksky_nearest_storm_distance
    - sensor.darksky_temperature
    - sensor.hallway_thermostat_humidity  
    - sensor.evening_commute
    - sensor.morning_commute
    - binary_sensor.kitchen_sensor_motion
    - binary_sensor.landing_sensor_motion
exclude:
  domains:
    - light
    - switch  
    - sensor
    - media_player
    - automation    
    - input_boolean
    - input_select