########################################
#                                      #
# This file defines what is logged in  #
# Home Assistant's History and Logbook #
#                                      #
########################################

include:
  domains:
    - device_tracker
    - person
  entities:
    - sensor.landing_sensor_temperature
exclude:
  domains:
    - sensor
    - media_player
    - input_boolean
    - input_select
    - light
    - climate
    - automation
    - switch
