#######################################################
#
#  This package contains components, sensor and
#  automations which are currently in a WIP state.
#
#
#######################################################


# @link https://developer.transportapi.com/docs?raml=https://transportapi.com/v3/raml/transportapi.raml##uk_public_journey_from_from_to_to_json
# Might be possible to eventually replace with direct calls to the json as they have apublic transport planner
sensor:
  - platform: uk_transport
    app_id: !secret uk_transport_id
    app_key: !secret uk_transport_key
    scan_interval:
      minutes: 20
    queries:
      # move to secrets.yaml
      - mode: train
        origin: !secret train_home
        destination: !secret train_sarah_work
      #- mode: train
      #  origin: !secret train_sarah_work
      #  destination: !secret train_home
      - mode: bus
        origin: !secret bus_am_start
        destination: !secret bus_am_end
      #- mode: bus
      #  origin: !secret bus_pm_start
      #  destination: !secret bus_pm_end

ios:
  push:
    categories:
      - name: Pre-Heat Home
        identifier: 'pre-heat-home'
        actions:
          - identifier: 'PREHEAT_YES'
            title: 'Yes'
            activationMode: 'background'
            authenticationRequired: false
          - identifier: 'PREHEAT_NO'
            title: 'No'
            activationMode: 'background'
            authenticationRequired: false


automation:




  # Starts playing Spotify on my phone at 8:15 on workdays
#  - alias: "Commute Start Spotify"
#    trigger:
#      platform: time
#      at: '08:15:00'
#    condition:
#      condition: and
#      conditions:
#        - condition: state
#          entity_id: 'binary_sensor.workday_sensor'
#          state: 'on'
#        - condition: state
#          entity_id: person.matt
#          state: 'home'
#        - condition: state
#          entity_id: input_boolean.alarm_clock
#          state: 'on'
#    action:
#      - service: media_player.select_source
#        entity_id: media_player.spotify
#        data:
#          source: "Matt's iPhone 8+"
#      - service: media_player.shuffle_set
#        data:
#         entity_id: media_player.spotify
#         shuffle: false



  #- alias: "Pre-heat home"
  #  trigger:
  #    - platform: zone
  #      entity_id: person.sarah
  #      zone: zone.sarah_work
  #      event: leave
  #  condition:
  #    condition: and
  #    conditions:
  #      - condition: state
  #        entity_id: 'binary_sensor.workday_sensor'
  #        state: 'on'
  #      - condition: time
  #        after: '15:00:00'
  #      - condition: numeric_state
  #        entity_id: sensor.average_home_temperature
  #        below: 16
  #  action:
  #    - service: notify.mobile_app_matts_phone
  #      data_template:
  #        title: >
  #          {{ "\uD83C\uDF21" }} It's a little chilly at home
  #        message: "Hi Sarah, it's currently {{ states.sensor.average_home_temperature.state }}°C at home. Would you like me to pre-heat the house?"
  #        data:
  #          push:
  #            category: "pre-heat-home"

  # climate.set_operation_mode doesn't appear to be working here...
  - alias: "Pre-heat home YES"
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: PREHEAT_YES
    action:
      - service: notify.mobile_app_matts_phone
        data_template:
          message: >
            {{ "\uD83C\uDF21" }} OK, I've turned the thermostat on. See you soon.
      - service: climate.set_hvac_mode
        data:
          entity_id: climate.hallway
          operation_mode: heat_cool
      - service: climate.set_temperature
        data:
          entity_id: climate.hallway
          temperature: 20
