#######################################################
#
#  This package contains components, sensor and
#  automations which are currently in a WIP state.
#
#
#######################################################

homeassistant:
  customize:
    binary_sensor.back_door_sensor:
      icon: mdi:door
    binary_sensor.front_door_sensor:
      icon: mdi:door


# iCal integration - doesn't seem to pull any calendar info in

#calendar:
#  - platform: caldav
#    url: !secret icloud_cal_url
#    username: !secret icloud_email
#    password: !secret icloud_specific_password
#    calendars:
#      - 'Joint'
#      - 'Sarah'
#      - 'Home'

#sensor:
#  - platform: uk_transport
#    app_id: !secret uk_transport_id
#    app_key: !secret uk_transport_key
#    queries:
#      - mode: train
#        origin: SOU
#        destination: WIN

# Add support for person component

ios:
  push:
    categories:
      - name: Pre-Heat Home
        identifier: 'pre-heat-home'
        actions:
          - identifier: 'PREHEAT_YES'
            title: 'Yes'
            activationMode: 'background'
            authenticationRequired: false
          - identifier: 'PREHEAT_NO'
            title: 'No'
            activationMode: 'background'
            authenticationRequired: false

notify:
  - platform: html5
    name: HTML
    gcm_api_key: !secret google_notify_api_key
    gcm_sender_id: !secret google_notify_sender_id

# GOOGLE CALENDARS
google:
  client_id: 859387401107-51hpivpp2dnan3alrlvbe98n9ar3a87f.apps.googleusercontent.com
  client_secret: 1BS_q90gr-tRn0AmfWWItXjy

automation:

#  - alias: 'Theme Switch'
#    hide_entity: True
#    trigger:
#      - platform: homeassistant
#        event: start
#      - platform: state
#        entity_id: sun.sun
#    action:
#      - service_template: frontend.set_theme
#        data_template:
#          name: >
#            {% if states.sun.sun.state == "above_horizon" %}
#              modern
#            {% else %}
#              modern-dark
#            {% endif %}
  # Starts playing Spotify on my phone at 8:15 on workdays
  - alias: "Commute Start Spotify"
    hide_entity: true
    trigger:
      platform: time
      at: '08:15:00'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: 'binary_sensor.workday_sensor'
          state: 'on'
        - condition: state
          entity_id: person.matt
          state: 'home'
        - condition: state
          entity_id: input_boolean.alarm_clock
          state: 'on'
    action:
      - service: media_player.select_source
        entity_id: media_player.spotify
        data:
          source: "Matt's iPhone 8+"
      - service: media_player.shuffle_set
        data:
         entity_id: media_player.spotify
         shuffle: false
  - alias: 'Notify of Sonarr / Radarr activity'
    trigger:
      - platform: template
        value_template: '{{ states.persistent_notification.notification.attributes.title == "Sonarr" }}'
      - platform: template
        value_template: '{{ states.persistent_notification.notification.attributes.title == "Radarr" }}'
    action:
      - service: notify.all_phones
        data_template:
          title: 'Incoming Media'
          message: '{{ "\uD83C\uDFAC" }} {{ states.persistent_notification.notification.attributes.message }}'
      - service: persistent_notification.dismiss
        data_template:
          notification_id: "{{ trigger.to_state.attributes.object_id }}"

  - alias: "Pre-heat home"
    trigger:
      - platform: zone
        entity_id: device_tracker.sarah
        zone: zone.sarah_work
        event: leave
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: 'binary_sensor.workday_sensor'
          state: 'on'
        - condition: time
          after: '15:30:00'
        - condition: numeric_state
          entity_id: sensor.average_home_temperature
          below: 16
    action:
      - service: notify.ios_sarah
        data_template:
          title: >
            {{ "\uD83C\uDF21" }} It's a little chilly at home
          message: "Hi Sarah, it's currently {{ states.sensor.average_home_temperature.state }}°C at home. Would you like me to pre-heat the house?"
          data:
            push:
              category: "pre-heat-home"

  # climate.set_operation_mode doesn't appear to be working here...
  - alias: "Pre-heat home YES"
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: PREHEAT_YES
    action:
      - service: notify.ios_sarah
        data_template:
          message: >
            {{ "\uD83C\uDF21" }} OK, I've turned the thermostat on. See you soon.
      - service: climate.set_hvac_mode
        data:
          entity_id: climate.hallway
          operation_mode: heat_cool
      - service: climate.set_temperature
        data:
          entity_id: climate.hallway
          temperature: 20

#  - alias: Automatic Theme Change
#    trigger:
#      - platform: homeassistant
#        event: start
#      - platform: state
#        entity_id: sun.sun
#    action:
#      - service_template: frontend.set_theme
#        data_template:
#          name: >
#            {% if states.sun.sun.state == "above_horizon" %}
#              modern
#            {% else %}
#              modern-dark
#            {% endif %}


# for huesensor component
#sensor:
#  - platform: template
#    sensors:
#      kitchen_temperature:
#       value_template: '{{ states.sensor.kitchen_motion_sensor.attributes["temperature"] }}'
#        friendly_name: 'Kitchen Temperature'
#        unit_of_measurement: '°C'
#      landing_temperature:
#        value_template: '{{ states.sensor.landing_motion_sensor.attributes["temperature"] }}'
#        friendly_name: 'Landing Temperature'
#        unit_of_measurement: '°C'
#      kitchen_humidity:
#        value_template: '{{ states.sensor.kitchen_motion_sensor.attributes["humidity"] }}'
#        friendly_name: 'Kitchen Humidity'
#        unit_of_measurement: '%'
#      landing_humidity:
#        value_template: '{{ states.sensor.landing_motion_sensor.attributes["humidity"] }}'
#        friendly_name: 'Landing Humidity'
#        unit_of_measurement: '%'


  # Turn on the Lounge lights with the TV when it's dark out
  #- alias: 'Scene - Lounge Evening'
  #  hide_entity: true
  #  trigger:
  #  - platform: state
  #    entity_id: media_player.philips_tv
  #    to: 'on'
  #    from: 'off'
  #  condition:
  #  - condition: numeric_state
  #    entity_id: sensor.outside_light_level
  #    below: 5.0
  #  action:
  #  - service: input_select.select_option
  #    data:
  #      entity_id: input_select.scene_lounge
  #      option: "Relax"
