automation:
  - alias: "MC Start Robbie"
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: magic_cube
          event: 6001
      - platform: event
        event_type: deconz_event
        event_data:
          id: magic_cube
          event: 6002
      - platform: event
        event_type: deconz_event
        event_data:
          id: magic_cube
          event: 6003
      - platform: event
        event_type: deconz_event
        event_data:
          id: magic_cube
          event: 6004
      - platform: event
        event_type: deconz_event
        event_data:
          id: magic_cube
          event: 6005
    action:
      - service: vacuum.start
        data:
          entity_id: vacuum.rockrobo
