#######################################################
#                                                     #
#               PACKAGES / MEDIA CENTER              #
#                                                     #
#######################################################


#######################################################
#                                                     #
#                       SENSOR                        #
#                                                     #
#######################################################

sensor:

## HOME ASSISTANT STATISTICS
  - platform: radarr
    host: !secret ip_nuc
    port: !secret radarr_port
    api_key: !secret radarr_api
    days: 14
    monitored_conditions:
#      - movies
      - upcoming
#      - commands
      - status

  - platform: sonarr_upcoming_media
    api_key: !secret sonarr_api
    host: !secret ip_nuc
    port: !secret sonarr_port
    days: 14
    ssl: false
    max: 10

  - platform: radarr_upcoming_media
    api_key: !secret radarr_api
    host: !secret ip_nuc
    port: !secret radarr_port
    days: 62
    ssl: false
    max: 10

#######################################################
#                                                     #
#                    INTEGRATIONS                     #
#                                                     #
#######################################################

sabnzbd:
  api_key: !secret sabnzbd_api_key
  host: !secret ip_nuc
  port: !secret sabnzbd_port
  ssl: true
  name: SABnzbd
