homeassistant:
  customize_glob:
    "script.vacuum*":
      icon: mdi:robot-vacuum

# Vaccum flashed with Valetudo using rrcc app on mac https://github.com/rand256/valetudo
# rrcc https://github.com/LazyT/rrcc
# See reddit guide https://www.reddit.com/r/homeassistant/comments/fdrcz0/how_to_install_valetudo_re_on_a_xiaomi_robot/
# Another guide at https://community.home-assistant.io/t/xiaomi-vacuum-with-valetudo-re-how-to-map-zoned-cleaning-and-notifications-with-home-assistant/172282/20
# Used DustBuilder to generate firmware https://builder.dontvacuum.me/
# To reset, hold power button and wifi - this will reset to factory settings
# Access Valetudo front end by visiting IP Address of Robbie whilst on local network
# SSH Password is stored in secrets


# DEPRECATED AS OF MARCH 2021 IN FAVOUR OF RUNNING VALETUDO
# vacuum:
#   - platform: xiaomi_miio
#     friendly_name: Robbie
#     host: !secret ip_robbie
#     token: !secret token_robbie

vacuum:
  - platform: mqtt
    name: "Robbie the Rover"

#panel_iframe:
#  valetudo:
#    title: "Valetudo"
#    url: !secret valetudo_url
#    icon: mdi:robot-vacuum


automation:
  - alias: Daily Vacuum
    trigger:
      - platform: time
        at: '16:00:00'
    condition:
# TODO: DONT RUN IF TV ON
      condition: not
      conditions:
        - condition: state
          entity_id: input_select.home_status
          state: "Holiday"
    action:
      - service: vacuum.start
        entity_id: vacuum.rockrobo
  - alias: Morning Vacuum Away
    trigger:
      - platform: time
        at: '10:00:00'
    condition:
      condition: not
      conditions:
        - condition: state
          entity_id: input_select.home_status
          state: "Home"
    action:
      - service: vacuum.start
        entity_id: vacuum.rockrobo





  ## Whenever Robbie becomes docked, increment counter
  - alias: Vacuum Counter Increment
    trigger:
      - platform: state
        entity_id: vacuum.rockrobo
        to: 'docked'
    action:
      - service: counter.increment
        entity_id: counter.vacuum_counter

  ## Reset Robbie Counter
  - alias: Vacuum Counter Reset
    trigger:
      - platform: state
        entity_id: counter.vacuum_counter
        to: '5'
    condition:
      - condition: state
        entity_id: vacuum.rockrobo
        state: 'docked'
    action:
      - service: counter.reset
        entity_id: counter.vacuum_counter

  ## If robbie has cleaned four times, send him to the bin for cleaning
  - alias: Vacuum Goto Bin
    trigger:
      - platform: state
        entity_id: counter.vacuum_counter
        to: '4'
    condition:
      - condition: state
        entity_id: vacuum.rockrobo
        state: 'docked'
    action:
      - service: script.tts_engine
        data_template:
          media_player: media_player.speakergroup_downstairs
          call_no_greeting: 1
          call_no_signoff: 1
          call_empty_robbie: 1
          tts_message: ""
      - service: script.notify_engine
        data_template:
          notify_title: "{{ '\uD83E\uDDF9'}} Empty Robbie's Bin"
          notify_message: >
            {% set hoover_amount = states.counter.vacuum_counter.state %}
            {{ [
            "Robbie has hoovered " ~ hoover_amount + " times without being cleaned - it's probably time his bin was emptied!",
            "It's about Robbie was mucked out. Please empty his bin.",
            "What does a bin have to do around here to get emptied! Robbie has hoovered " ~ hoover_amount + " times!",
            "I am full of Hercules' fluff and Ripley's droppings. Please empty me.",
            "HEY! YOU! CLEAN ME!",
            "Hello! Is anybody out there?! I could do with my bin being emptied please.",
            "I'm full up. Please empty me.",
            "My eyes are bigger than my belly. I'm full! Please empty me.",
            "Bleep, bloop I'm full of poop."
            ] | random }}
      - service: vacuum.send_command
        data:
          entity_id: vacuum.rockrobo
          command: app_goto_target
          params: [19800,26000]

  ## If robbie has cleaned four times, send a notification prompting to clean his bins, and reset the counter
  - alias: Vacuum Notify Clean Bin
    trigger:
      - platform: state
        entity_id: input_select.home_status
        to: 'Home'
        for: 00:03:00
    condition:
      - condition: state
        entity_id: counter.vacuum_counter
        state: '4'
    action:
      - service: script.notify_engine
        data_template:
          notify_title: "{{ '\uD83E\uDDF9'}} Empty Robbie's Bin"
          notify_message: >
            {% set hoover_amount = states.counter.vacuum_counter.state %}
            {{ [
            "Robbie has hoovered " ~ hoover_amount + " times without being cleaned - it's probably time his bin was emptied!",
            "It's about Robbie was mucked out. Please empty his bin.",
            "What does a bin have to do around here to get emptied! Robbie has hoovered " ~ hoover_amount + " times!",
            "I am full of Hercules' fluff and Ripley's droppings. Please empty me.",
            "HEY! YOU! CLEAN ME!",
            "Hello! Is anybody out there?! I could do with my bin being emptied please.",
            "I'm full up. Please empty me.",
            "My eyes are bigger than my belly. I'm full! Please empty me.",
            "Bleep, bloop I'm full of poop."
            ] | random }}




counter:
  vacuum_counter:
    initial: 0
    step: 1
    icon: mdi:counter













# TODO: Check these are still working OK
script:
  vacuum_mop:
    alias: Vacuum - Mop
    sequence:
      - service: vacuum.set_fan_speed
        data:
          entity_id: vacuum.rockrobo
          fan_speed: 105
      - service: vacuum.send_command
        data:
          entity_id: vacuum.rockrobo
          command: app_start
  vacuum_go_home:
    alias: Vacuum - Go Home
    sequence:
      - service: vacuum.return_to_base
        data:
          entity_id: vacuum.rockrobo

  #@link https://community.home-assistant.io/t/howto-xiaomi-vacuum-zoned-cleaning/51293/22
  # Starting point is 25500,25500

  vacuum_come_out:
    alias: Vacuum - Come Out
    sequence:
      - service: vacuum.send_command
        data:
          entity_id: vacuum.rockrobo
          command: app_goto_target
          params: [26000,25600]

  #roborock_bins:
  #  alias: Roborock bins
  #  sequence:
  #    - service: vacuum.send_command
  #      data:
  #        entity_id: vacuum.rockrobo
  #        command: app_goto_target
  #        params: [31500, 27500]
