#######################################################
#
#  This package contains components, sensor and 
#  automations which are currently in a WIP state.
#
#
#######################################################

# iCal integration - doesn't seem to pull any calendar info in

#calendar:
#  - platform: caldav
#    url: !secret icloud_cal_url
#    username: !secret icloud_email
#    password: !secret icloud_specific_password
#    calendars:
#      - 'Joint' 
#      - 'Sarah'
#      - 'Home'
vacuum:
  - platform: xiaomi_miio
    friendly_name: Robbie
    host: !secret ip_robbie
    token: !secret token_robbie

spotcast:
  username: !secret spotify_username
  password: !secret spotify_password
    
media_player:
  - platform: philips_js
    host: !secret ip_philips_tv
    name: Philips TV
    api_version: 6
    
    
    
    
    
    
    
    
    
    
#sensor:
#  - platform: uk_transport
#    app_id: !secret uk_transport_id
#    app_key: !secret uk_transport_key
#    queries:
#      - mode: train
#        origin: SOU
#        destination: WIN       
        

# Add support for person component
#person:
#  - name: Matt
#    id: matt
#    user_id: 6727ee0d558348a5b33ea2b1534d5797
#    device_trackers:
#      - device_tracker.matt
#      - device_tracker.matt_ping
#      - device_tracker.matt_watch
#  - name: Sarah
#    id: sarah
#    user_id: d40377bd5d284df2bf051236544fafcb
#    device_trackers:
#      - device_tracker.sarah
#      - device_tracker.sarah_ping
#      - device_tracker.sarah_watch
    
ios:
  push:
    categories:
      - name: Pre-Heat Home
        identifier: 'pre-heat-home'
        actions:
          - identifier: 'PREHEAT_YES'
            title: 'Yes'
            activationMode: 'background'
            authenticationRequired: false
          - identifier: 'PREHEAT_NO'
            title: 'No'
            activationMode: 'background'
            authenticationRequired: false
         
#notify:
#  - platform: html5
#    name: HTML
#    gcm_api_key: !secret google_notify_api_key
#    gcm_sender_id: !secret google_notify_sender_id

# GOOGLE CALENDARS
google:
  client_id: 859387401107-msgiilto1gl8mpmcjvrlsjr7rrupfa48.apps.googleusercontent.com
  client_secret: 9U9-jHm_yI8TRpBn1I9aeyiE
      
automation:
  - alias: "Shuffle test"
    trigger:
      platform: time
      at: '08:15:00'
    action:
      - service: spotcast.start
        data_template:
          device_name: 'Bedroom Speaker'
          uri: >
            {{ [
            'spotify:user:spotify:playlist:37i9dQZEVXcHsW4pFj4T0C', 
            'spotify:user:spotify:playlist:37i9dQZEVXbtkYqvjNCAlq', 
            'spotify:user:spotify:playlist:37i9dQZF1DX4W3aJJYCDfV', 
            'spotify:user:spotify:playlist:37i9dQZF1DX32oVqaQE8BM',
            'spotify:user:spotify:playlist:37i9dQZF1DWWLToO3EeTtX'
            ] | random }}    
      - service: media_player.shuffle_set
        data:
         entity_id: media_player.spotify
         shuffle: true
      


  - alias: "Pre-heat home"
    trigger:
      - platform: zone
        entity_id: device_tracker.sarah
        zone: zone.sarah_work
        event: leave
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: 'binary_sensor.workday_sensor'
          state: 'on'
        - condition: time
          after: '15:30:00'
        - condition: numeric_state
          entity_id: sensor.average_home_temperature
          below: 16
    action:
      - service: notify.ios_sarah
        data_template: 
          title: >
            {{ "\uD83C\uDF21" }} It's a little chilly at home
          message: "Hi Sarah, it's currently {{ states.sensor.average_home_temperature.state }}°C at home. Would you like me to pre-heat the house?"
          data:
            push:
              category: "pre-heat-home"

  # climate.set_operation_mode doesn't appear to be working here...
  - alias: "Pre-heat home YES"
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: PREHEAT_YES
    action:
      - service: notify.ios_sarah
        data_template: 
          message: >
            {{ "\uD83C\uDF21" }} OK, I've turned the thermostat on. See you soon.
      - service: climate.set_operation_mode
        data:
          entity_id: climate.hallway
          operation_mode: "heat"
      - service: climate.set_temperature
        data:
          entity_id: climate.hallway
          temperature: 20

#  - alias: Automatic Theme Change
#    trigger:
#      - platform: homeassistant
#        event: start
#      - platform: state
#        entity_id: sun.sun
#    action:
#      - service_template: frontend.set_theme
#        data_template:
#          name: >
#            {% if states.sun.sun.state == "above_horizon" %}
#              modern
#            {% else %}
#              modern-dark
#            {% endif %}

      
automation:
  - alias: "Commute Start Spotify"
    hide_entity: true
    trigger:
      platform: time
      at: '08:15:00'
    condition:  
      condition: and
      conditions:
        - condition: state
          entity_id: 'binary_sensor.workday_sensor'
          state: 'on'
        - condition: state
          entity_id: sensor.is_matt_home
          state: 'home'
        - condition: state
          entity_id: input_boolean.alarm_clock
          state: 'on'
    action:
      - service: media_player.select_source
        entity_id: media_player.spotify
        data:
          source: "Matt's iPhone 8+"
      - service: media_player.shuffle_set
        data:
         entity_id: media_player.spotify
         shuffle: false
          