#######################################################
#
#  This package contains the components and sensors 
#  used to set up and monitor Home Assistant
#
#  ----------------------------------------------------
#
#  DEPENDS ON: Notifications
#  
#######################################################

homeassistant:
  customize_domain:
    script:
      hidden: true
  customize:
    script.restart_hass:
      hidden: false
      icon: mdi:restart
      friendly_name: Restart Home Assistant
  customize_glob:
    "automation.*scene*":
      icon: mdi:brightness-6  
      
http:
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  ip_ban_enabled: True
  login_attempts_threshold: 15
  base_url: !secret base_url
  trusted_networks:
  # Allow access to known devices without having to enter a password
    - !secret ip_macbook
    - !secret ip_matt_phone
    - !secret ip_sarah_phone
  
frontend:
  javascript_version: latest
  
system_health:
  
lovelace:
  mode: yaml
  
custom_updater:
  track:
    - cards
    - components
    - python_scripts
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
    - https://raw.githubusercontent.com/rdehuyss/homeassistant-lovelace-google-calendar-card/master/custom_updater.json
    - https://raw.githubusercontent.com/nervetattoo/simple-thermostat/master/tracker.json
  
config:

map:

recorder:
  # The Home Assistant db is saved on a USB to prolonge the life of the SD card.
  # Here we point to it's location
  db_url: sqlite:///mnt/usbdrive/home-assistant_v2.db
  purge_interval: 2
  purge_keep_days: 6
  
history: !include ../includes/logging.yaml

logbook: !include ../includes/logging.yaml

# Check for updates
updater:

#discovery:

api:

logger:
  default: warning
  logs:
    homeassistant.components.media_player.spotify: info

#######################################################
#                                                     #
#                     AUTOMATIONS                     #
#                                                     #
#######################################################

automation:
  - alias: 'Notify - HASS New Update'
    hide_entity: True
    trigger:
      - platform: state
        entity_id: updater.updater
    action:
      service: notify.matt
      data_template: 
        title: '{{ "\u2699\uFE0F"}} New Home Assistant Release'
        message: "Home Assistant  {{ states.updater.updater.state }}  is now available."
        
  - alias: 'Notify - HASS Start'
    hide_entity: True
    trigger:
      - platform: homeassistant
        event: start
    action:
      service: notify.matt
      data_template: 
        title: '{{ "\u2699\uFE0F"}} Home Assistant started'
        message: "Powering up..."
        
  - alias: 'Notify - HASS Shutdown'
    hide_entity: True
    trigger:
      - platform: homeassistant
        event: shutdown
    action:
      service: notify.matt
      data_template: 
        title: '{{ "\u2699\uFE0F"}} Home Assistant shut down'
        message: "Logging off..."