#######################################################
#
#  This package contains the components and sensors
#  used to set up and monitor Home Assistant
#
#  ----------------------------------------------------
#
#  DEPENDS ON: Notifications
#
#######################################################

homeassistant:
  customize_domain:
    script:
      hidden: true
  customize:
    script.restart_hass:
      hidden: false
      icon: mdi:restart
      friendly_name: Restart Home Assistant
  customize_glob:
    "automation.*scene*":
      icon: mdi:brightness-6

http:
  base_url: !secret base_url
#  ssl_certificate: /ssl/fullchain.pem
#  ssl_key: /ssl/privkey.pem
#  ssl_profile: intermediate
  ip_ban_enabled: True
  login_attempts_threshold: 15

frontend:
  javascript_version: latest
  themes: !include_dir_merge_named ../themes

system_health:

mobile_app:

lovelace:
  mode: yaml

config:

map:

recorder:
  #db_url: !secret db_url
  purge_interval: 2
  purge_keep_days: 6

history: !include ../includes/logging.yaml

logbook: !include ../includes/logging.yaml

# Check for updates
updater:

discovery:
  ignore:
    - igd

ssdp:
zeroconf:

api:

logger:
  default: info
#  logs:
#    homeassistant.components.media_player.spotify: info

#######################################################
#                                                     #
#                     AUTOMATIONS                     #
#                                                     #
#######################################################

automation:
  - alias: 'Notify - HASS New Update'
    hide_entity: True
    trigger:
      - platform: state
        entity_id: updater.updater
    action:
      service: notify.matt
      data_template:
        title: '{{ "\u2699\uFE0F"}} New Home Assistant Release'
        message: "Home Assistant  {{ states.updater.updater.state }}  is now available."

  - alias: 'Notify - HASS Start'
    hide_entity: True
    trigger:
      - platform: homeassistant
        event: start
    action:
      service: notify.matt
      data_template:
        title: '{{ "\u2699\uFE0F"}} Home Assistant started'
        message: "Powering up..."

  - alias: 'Notify - HASS Shutdown'
    hide_entity: True
    trigger:
      - platform: homeassistant
        event: shutdown
    action:
      service: notify.matt
      data_template:
        title: '{{ "\u2699\uFE0F"}} Home Assistant shut down'
        message: "Logging off..."
#  - alias: 'Theme Switch'
#    hide_entity: True
#    trigger:
#      - platform: homeassistant
#        event: start
#      - platform: state
#        entity_id: sun.sun
#    action:
#      - service_template: frontend.set_theme
#        data_template:
#          name: >
#            {% if states.sun.sun.state == "above_horizon" %}
#              modern
#            {% else %}
#              modern-dark
#            {% endif %}
