#######################################################
#
#  This package contains the components and sensors 
#  used to monitor and interact with household lights.
#  Automations include the dynamic setting of light based
#  on presence / time of day.
#
#  ----------------------------------------------------
#
#  DEPENDS ON: Occupancy, Scenes, Environment
#  
#######################################################

homeassistant:
  customize_domain:
    light:
      icon: mdi:ceiling-light
      
  customize:
    light.bedroom_entertainment_area:
      hidden: true
      homebridge_hidden: true
    light.all_hue_lights:
      hidden: true
      homebridge_hidden: true
    light.master_bedroom:
      homebridge_hidden: true
      icon: mdi:hotel
    light.dining_room:
      homebridge_hidden: true
      icon: mdi:silverware-variant
    light.guest_bedroom:
      homebridge_hidden: true
      icon: mdi:hotel
    light.lounge:
      homebridge_hidden: true
      icon: mdi:sofa
    light.office:
      homebridge_hidden: true
      icon: mdi:desktop-mac
    light.hallway:
      homebridge_hidden: true
      icon: mdi:stairs
    light.kitchen:
      homebridge_hidden: true
      icon: mdi:fridge
    light.landing:
      homebridge_hidden: true
      icon: mdi:stairs
    light.lounge_lamp:
      icon: mdi:lamp
    light.dining_room_lamp:
      icon: mdi:floor-lamp
    light.guest_bedroom_opihr:
      icon: mdi:lamp
    light.guest_bedroom_sovereign:
      icon: mdi:lamp
    light.office_lamp:
      icon: mdi:lamp
    light.hue_go:
      icon: mdi:circle
    light.master_bedroom_lightstrip:
      icon: mdi:led-strip
      
    sensor.guest_bedroom_switch:
      hidden: true
    sensor.master_bedroom_switch:
      hidden: true
    sensor.office_switch:
      hidden: true
    binary_sensor.kitchen_sensor_motion:
      hidden: true
    binary_sensor.landing_sensor_motion:
      hidden: true
    sensor.landing_temperature:
      icon: mdi:thermometer
    sensor.kitchen_temperature:
      icon: mdi:thermometer

hue:
  bridges:
    - host: !secret ip_hue_hub
      allow_unreachable: true
      allow_hue_groups: true

#sensor:
#  - platform: hue_sensor
#  - platform: template
#    sensors:
#      kitchen_temperature:
#       value_template: '{{ states.sensor.kitchen_motion_sensor.attributes["temperature"] }}'
#        friendly_name: 'Kitchen Temperature'
#        unit_of_measurement: '°C'
#      landing_temperature:
#        value_template: '{{ states.sensor.landing_motion_sensor.attributes["temperature"] }}'
#        friendly_name: 'Landing Temperature'
#        unit_of_measurement: '°C'
#      kitchen_humidity:
#        value_template: '{{ states.sensor.kitchen_motion_sensor.attributes["humidity"] }}'
#        friendly_name: 'Kitchen Humidity'
#        unit_of_measurement: '%'
#      landing_humidity:
#        value_template: '{{ states.sensor.landing_motion_sensor.attributes["humidity"] }}'
#        friendly_name: 'Landing Humidity'
#        unit_of_measurement: '%'
      
#######################################################
#                                                     #
#                     AUTOMATIONS                     #
#                                                     #
#######################################################

automation:
  # TURN ALL LIGHTS OFF AT 10AM
  - alias: 'Lights Off at 10am'
    hide_entity: true
    trigger:
      - platform: time
        at: '10:00:00'
    condition:
      - condition: state
        entity_id: group.all_lights
        state: 'on'
    action:
      - service: light.turn_off
        entity_id: group.all_lights

  # TURN THE HALLWAY LIGHT ON BETWEEN 2100-0500 IF ANYONE ARRIVES HOME
  - alias: 'Hallway light on if late home'
    hide_entity: true
    trigger: 
      - platform: state
        entity_id: sensor.is_matt_home, sensor.is_sarah_home
        from: 'not_home'
        to: 'home'
    condition:
      condition: and
      conditions:
        - condition: time
          after: '21:00:00'
          before: '05:00:00'
        - condition: state
          entity_id: sun.sun
          state: 'below_horizon'
    action:
      - service: scene.turn_on
        entity_id: scene.hallway_dimmed
      - delay: '00:10:00'
      - service: light.turn_off
        entity_id: light.hallway
        
  # Turn on the dining room and hallway light when it gets darker outside
  - alias: 'Scene - Dining Room Early Evening'
    hide_entity: true
    trigger:
    - platform: numeric_state
      entity_id: sensor.outside_light_level
      below: 5.0
    - platform: state
      entity_id: input_select.home_status
      to: "Home"
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_select.home_status
          state: "Home"
        - condition: numeric_state
          entity_id: sensor.outside_light_level
          below: 5.0
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.scene_dining_room
          option: "Relax"
      - service: scene.turn_on
        entity_id: scene.hallway_dimmed
   
  # Turn on the Lounge lights with the TV when it's dark out
  - alias: 'Scene - Lounge Evening'
    hide_entity: true
    trigger:
    - platform: state
      entity_id: media_player.lounge_tv
      to: 'playing'
      from: 'off'
    condition:
    - condition: numeric_state
      entity_id: sensor.outside_light_level
      below: 5.0
    action:
    - service: input_select.select_option
      data:
        entity_id: input_select.scene_lounge
        option: "Relax"