#######################################################
#
#  This package contains the components used to set up
#  and manage switches
#
#######################################################

homeassistant:
  customize_domain:
    switch:
      icon: mdi:power-plug
  customize:
    switch.tuya_1:
      icon: mdi:star-four-points
      friendly_name: Fairy Lights
    switch.tuya_2:
      icon: mdi:lamp
      friendly_name: Star Lamp
    switch.tuya_3:
      icon: mdi:white-balance-incandescent
      friendly_name: Festoon Lights

tuya:
  username: !secret tuya_user
  password: !secret tuya_pass
  country_code: 44
  platform: smart_life

tplink:

input_boolean:
  doorbell_pressed:
    name: Doorbell Pressed
    initial: off
    icon: mdi:bell-ring


#######################################################
#                                                     #
#                     AUTOMATIONS                     #
#                                                     #
#######################################################

# @link https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Xiaomi-WXKG01LM

automation:
  - alias: "Doorbell"
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: switch_5
          event: 1000
    condition:
      - condition: state
        entity_id: input_boolean.doorbell_pressed
        state: 'off'
    action:
      - service: notify.matt
        data_template:
          title: >
            {{ "\ud83d\udd14" }} Someone's at the door!
          message: "The doorbell has been pressed."
      - service: media_player.play_media
        data_template:
          entity_id: media_player.speakers
          media_content_id: https://home.lynwood.club/local/doorbell.mp3
          media_content_type: 'audio/mp3'
      - service: input_boolean.turn_on
        entity_id: input_boolean.doorbell_pressed

  - alias: "Reset Doorbell"
    trigger:
      platform: state
      entity_id: input_boolean.doorbell_pressed
      to: 'on'
      for:
        seconds: 6
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.doorbell_pressed
