#######################################################
#
#  This package contains the components used for Magic
#  Cube automations
#
#  @link https://github.com/dresden-elektronik/deconz-rest-plugin/issues/138#issuecomment-325101635
#  @link https://community.home-assistant.io/t/xiaomi-cube-rotate/34186/37
#
#######################################################


#######################################################
#                                                     #
#                     AUTOMATIONS                     #
#                                                     #
#######################################################

automation:
  - alias: "MC Start Robbie"
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: magic_cube
          event: 6001
      - platform: event
        event_type: deconz_event
        event_data:
          id: magic_cube
          event: 6002
      - platform: event
        event_type: deconz_event
        event_data:
          id: magic_cube
          event: 6003
      - platform: event
        event_type: deconz_event
        event_data:
          id: magic_cube
          event: 6004
      - platform: event
        event_type: deconz_event
        event_data:
          id: magic_cube
          event: 6005
    action:
      - service: vacuum.start
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
