homeassistant:
  customize_domain:
    switch:
      icon: mdi:power-plug
  customize:
    switch.fairy_lights:
      icon: mdi:star-four-points
      friendly_name: Fairy Lights
    switch.star_lamp:
      icon: mdi:lamp
      friendly_name: Star Lamp
    switch.festoon_lights:
      icon: mdi:white-balance-incandescent
      friendly_name: Festoon Lights

tuya:
  username: !secret tuya_user
  password: !secret tuya_pass
  country_code: 44
  platform: smart_life

tplink:
