homeassistant:
  customize_domain:
    switch:
      icon: mdi:power-plug
  customize:
    switch.tuya_1:
      icon: mdi:star-four-points
      friendly_name: Fairy Lights
    switch.tuya_2:
      icon: mdi:lamp
      friendly_name: Star Lamp
    switch.tuya_3:
      icon: mdi:white-balance-incandescent
      friendly_name: Festoon Lights

tuya:
  username: !secret tuya_user
  password: !secret tuya_pass
  country_code: 44
  platform: smart_life

tplink:
