#######################################################
#                                                     #
#              PACKAGES / HOME ASSISTANT              #
#                                                     #
#######################################################

homeassistant:
  customize:
    script.restart_hass:
      icon: mdi:restart
      friendly_name: Restart Home Assistant
    automation.hass_notify_new_release:
      icon: mdi:alert-decagram
    automation.hass_notify_system_start:
      icon: mdi:power
    automation.hass_notify_system_shutdown:
      icon: mdi:power
    binary_sensor.updater:
      icon: mdi:alert-decagram

#######################################################
#                                                     #
#                     AUTOMATIONS                     #
#                                                     #
#######################################################

automation:
  - alias: Hass Notify - New Release
    hide_entity: True
    trigger:
      - platform: state
        entity_id: updater.updater
    action:
      service: notify.matt
      data_template:
        title: '{{ "\u2699\uFE0F"}} New Home Assistant Release'
        message: "Home Assistant  {{ states.updater.updater.state }}  is now available."

  - alias: Hass Notify - System Start
    hide_entity: True
    trigger:
      - platform: homeassistant
        event: start
    action:
      service: notify.matt
      data_template:
        title: '{{ "\u2699\uFE0F"}} Home Assistant started'
        message: "Powering up..."

  - alias: Hass Notify - System Shutdown
    hide_entity: True
    trigger:
      - platform: homeassistant
        event: shutdown
    action:
      service: notify.matt
      data_template:
        title: '{{ "\u2699\uFE0F"}} Home Assistant shut down'
        message: "Until next time..."

#######################################################
#                                                     #
#                       SCRIPTS                       #
#                                                     #
#######################################################

script:
  restart_hass:
    sequence:
      - service: homeassistant.restart
