#######################################################
#                                                     #
#              PACKAGES / HOME ASSISTANT              #
#                                                     #
#######################################################

homeassistant:
  customize_glob:
    "*version*":
      icon: mdi:package-up
  customize:
    script.restart_hass:
      icon: mdi:restart
      friendly_name: Restart Home Assistant
    script.clear_caches:
      icon: mdi:delete
      friendly_name: Clear DB/Log/TTS
    automation.hass_notify_new_release:
      icon: mdi:alert-package-up
    automation.hass_notify_system_start:
      icon: mdi:power
    automation.hass_notify_system_shutdown:
      icon: mdi:power
    binary_sensor.updater:
      icon: mdi:alert-package-up
    automation.theme_switch:
      icon: mdi:view-quilt

#######################################################
#                                                     #
#                       SENSOR                        #
#                                                     #
#######################################################

sensor:
  ## HA version
  - platform: version
    name: Installed Version

  ## HA available version
  - platform: version
    name: Latest Available Version
    beta: false
    source: hassio

#######################################################
#                                                     #
#                     AUTOMATIONS                     #
#                                                     #
#######################################################

automation:
  - alias: Hass Notify - New Release
    trigger:
      - platform: state
        entity_id: updater.updater
    action:
      service: notify.matt_all
      data_template:
        title: '{{ "\u2699\uFE0F"}} New Home Assistant Release'
        message: "Home Assistant  {{ states.updater.updater.state }}  is now available."
        data:
          push:
            thread-id: "hass-notifications"

  - alias: Hass Notify - System Start
    trigger:
      - platform: homeassistant
        event: start
    action:
      service: notify.matt_all
      data_template:
        title: '{{ "\u2699\uFE0F"}} Home Assistant started'
        message: "Powering up..."
        data:
          push:
            thread-id: "hass-notifications"

  - alias: Hass Notify - System Shutdown
    trigger:
      - platform: homeassistant
        event: shutdown
    action:
      service: notify.matt_all
      data_template:
        title: '{{ "\u2699\uFE0F"}} Home Assistant shut down'
        message: "Until next time..."
        data:
          push:
            thread-id: "hass-notifications"

  ## SWITCHES BETWEEN LIGHT/DARK THEMES AT SUNSET/SUNRISE
  - alias: 'Theme Switch'
    trigger:
      - platform: homeassistant
        event: start
      - platform: sun
        event: sunset
      - platform: sun
        event: sunrise
    action:
      - service_template: frontend.set_theme
        data_template:
          name: >
            {% if states.sun.sun.state == "above_horizon" %}
              lynwood-clear
            {% else %}
              lynwood-synthwave
            {% endif %}

#######################################################
#                                                     #
#                       SCRIPTS                       #
#                                                     #
#######################################################

script:
  restart_hass:
    sequence:
      - service: homeassistant.restart
  clear_caches:
    sequence:
      - service: tts.clear_cache
      - service: recorder.purge
      - service: system_log.clear
