#######################################################
#                                                     #
#              PACKAGES / TRACKED DEVICES             #
#                                                     #
#######################################################

homeassistant:

  customize_glob:
    "*sensor*router*":
      icon: mdi:router-wireless
    "*sensor*mycloud*":
      icon: mdi:nas
    "*sensor*server*":
      icon: mdi:server-network
    "*sensor*range_extender*":
      icon: mdi:wifi
    "*sensor*hue_hub*":
      icon: mdi:home-lightbulb
    "*sensor*nest*":
      icon: mdi:thermostat
    "*sensor*robbie_the_rover*":
      icon: mdi:robot-vacuum
    "*sensor*playstation_4*":
      icon: mdi:playstation
    "*sensor*nintendo_switch*":
      icon: mdi:nintendo-switch
    "*sensor*lounge_tv*":
      icon: mdi:television
    "*sensor*macbook*":
      icon: mdi:laptop-mac
    "*sensor*imac*":
      icon: mdi:desktop-mac
    "*sensor*sarah_ipad*":
      icon: mdi:tablet-ipad
    "*sensor*heated_blanket*":
      icon: mdi:power-plug
    "*sensor*star_lamp*":
      icon: mdi:power-plug
    "*sensor*fairy_lights*":
      icon: mdi:power-plug
    "*sensor*festoon_lights*":
      icon: mdi:power-plug
    #"*sensor*christmas_tree*":
    #  icon: mdi:power-plug
    #"*sensor*snowflakes*":
    #  icon: mdi:power-plug
    "*sensor*speaker*":
      icon: mdi:speaker

    automation.disconnected_device_notify:
      icon: mdi:minus-circle

#######################################################
#                                                     #
#                   BINARY SENSORS                    #
#                                                     #
#######################################################

binary_sensor:

  ## SERVER
  - platform: ping
    host: !secret ip_router
    name: Router
  - platform: ping
    host: !secret ip_mycloud
    name: MyCloud
  - platform: ping
    host: !secret ip_nuc
    name: Server
  - platform: ping
    host: !secret ip_range_extender_office
    name: Range Extender (Office)
  - platform: ping
    host: !secret ip_range_extender_kitchen
    name: Range Extender (Kitchen)

  ## INTEGRATIONS
  - platform: ping
    host: !secret ip_hue_hub
    name: Hue Hub
  - platform: ping
    host: !secret ip_nest
    name: Nest
  - platform: ping
    host: !secret ip_robbie
    name: Robbie the Rover

  ## ENTERTAINMENT
  - platform: ping
    host: !secret ip_playstation_4
    name: Playstation 4
  - platform: ping
    host: !secret ip_philips_tv
    name: Lounge TV
  - platform: ping
    host: !secret ip_nintendo_switch
    name: Nintendo Switch

  ## DEVICES
  - platform: ping
    host: !secret ip_macbook
    name: Macbook
  - platform: ping
    host: !secret ip_imac
    name: iMac
  - platform: ping
    host: !secret ip_sarah_ipad
    name: Sarah iPad

  ## SWITCHES
  - platform: ping
    host: !secret ip_switch_heated_mattress
    name: Heated Blanket
  - platform: ping
    host: !secret ip_switch_fairy_lights
    name: Fairy Lights
  - platform: ping
    host: !secret ip_switch_star_lamp
    name: Star Lamp
  - platform: ping
    host: !secret ip_switch_festoon_lights
    name: Festoon Lights
  #- platform: ping
  #  host: !secret ip_switch_snowflakes
  #  name: Snowflakes
  #- platform: ping
  #  host: !secret ip_switch_christmas_tree
  #  name: Christmas Tree

  ## SPEAKERS
  - platform: ping
    host: !secret ip_google_home_bedroom
    name: Bedroom Speaker
  - platform: ping
    host: !secret ip_google_home_lounge
    name: Lounge Speaker
  - platform: ping
    host: !secret ip_google_home_office
    name: Office Speaker
  - platform: ping
    host: !secret ip_google_home_dining
    name: Dining Room Speaker

#######################################################
#                                                     #
#                     AUTOMATIONS                     #
#                                                     #
#######################################################

automation:
  - alias: Disconnected Device Notify
    trigger:
      - platform: state
        entity_id: binary_sensor.router, binary_sensor.mycloud, binary_sensor.server, binary_sensor.range_extender_office, binary_sensor.range_extender_kitchen, binary_sensor.hue_hub, binary_sensor.robbie_the_rover, binary_sensor.heated_blanket, binary_sensor.star_lamp, binary_sensor.fairy_lights, binary_sensor.festoon_lights, binary_sensor.bedroom_speaker, binary_sensor.lounge_speaker, binary_sensor.office_speaker, binary_sensor.dining_room_speaker
        to: 'off'
    action:
      - service: notify.matt
        data_template:
          title: >
            {{ "\uD83D\uDED1" }} Device Disconnected
          message: "The {{ trigger.to_state.attributes.friendly_name }} has disconnected from the router."
